import type { Tool } from "../types";

export const financeTools: Tool[] = [
  {
    slug: "emi-calculator",
    category: "finance",
    name: "EMI Calculator",
    h1: "EMI Calculator",
    tagline: "Calculate your monthly loan EMI, total interest and total payment.",
    title: "EMI Calculator — Free Online Loan EMI Calculator (India)",
    description:
      "Free EMI calculator. Find your monthly loan EMI, total interest and total payable for home, car or personal loans. Instant, accurate, mobile-friendly.",
    intro:
      "Work out the Equated Monthly Instalment (EMI) for any loan — home, car, personal or business. Enter the loan amount, annual interest rate and tenure to see your monthly EMI, the total interest you'll pay, and the total amount payable over the loan.",
    keywords: ["emi calculator", "loan emi calculator", "home loan emi", "car loan emi calculator"],
    component: "emi-calculator",
    volumeEstimate: 2740000,
    howTo: [
      "Enter the loan (principal) amount.",
      "Enter the annual interest rate (%).",
      "Enter the tenure in months or years.",
      "See your monthly EMI, total interest and total payment update instantly.",
    ],
    faqs: [
      { q: "How is EMI calculated?", a: "EMI = P × r × (1+r)^n / ((1+r)^n − 1), where P is the principal, r is the monthly interest rate (annual rate ÷ 12 ÷ 100), and n is the number of monthly instalments." },
      { q: "Does a longer tenure reduce my EMI?", a: "Yes — a longer tenure lowers the monthly EMI, but you pay more total interest over the life of the loan. The calculator shows that trade-off clearly." },
      { q: "Is this EMI calculator accurate for home loans?", a: "Yes. The reducing-balance formula it uses is the standard method banks apply for home, car and personal loans on a fixed interest rate." },
    ],
    related: ["sip-calculator", "gst-calculator"],
  },
  {
    slug: "sip-calculator",
    category: "finance",
    name: "SIP Calculator",
    h1: "SIP Calculator",
    tagline: "Estimate the future value of your monthly mutual fund SIP.",
    title: "SIP Calculator — Free Mutual Fund SIP Returns Calculator",
    description:
      "Free SIP calculator. Estimate the maturity value and total returns of your monthly mutual fund SIP based on amount, tenure and expected return.",
    intro:
      "See how a monthly Systematic Investment Plan (SIP) could grow. Enter your monthly investment, the expected annual return and the duration to estimate the maturity value, the total amount you invested, and the wealth gained through compounding.",
    keywords: ["sip calculator", "mutual fund sip calculator", "sip return calculator", "sip maturity calculator"],
    component: "sip-calculator",
    volumeEstimate: 3350000,
    howTo: [
      "Enter your monthly SIP amount.",
      "Enter the expected annual return (%).",
      "Enter the investment duration in years.",
      "See the estimated maturity value and total gains instantly.",
    ],
    faqs: [
      { q: "How does a SIP calculator work?", a: "It applies the future-value-of-a-series formula: M = P × [((1+i)^n − 1) / i] × (1+i), where P is the monthly amount, i is the monthly return (annual ÷ 12 ÷ 100), and n is the number of months." },
      { q: "Are the returns guaranteed?", a: "No. Mutual fund returns are market-linked and vary. The calculator uses an assumed constant rate to project an estimate — actual results will differ." },
      { q: "What return rate should I assume?", a: "Many investors model equity SIPs at around 10–12% per year for long-term planning, but this is only an assumption — adjust it to your own expectations." },
    ],
    related: ["emi-calculator", "gst-calculator"],
  },
  {
    slug: "gst-calculator",
    category: "finance",
    name: "GST Calculator",
    h1: "GST Calculator (India)",
    tagline: "Add or remove GST at 5%, 18% or any other slab in seconds.",
    title: "GST Calculator — Add or Remove GST Online (India)",
    description:
      "Free GST calculator for India. Add GST to a base price or remove GST from an inclusive price at 5%, 18% or other slabs. See CGST/SGST split instantly.",
    intro:
      "Calculate GST both ways: add GST to a net amount to get the gross price, or remove GST from a GST-inclusive price to find the base amount. Pick a rate — 5% and 18% are the main slabs since the September 2025 rationalisation, with legacy 12%/28% and the 40% demerit rate also supported — and see the GST amount, the total, and the CGST/SGST split.",
    keywords: ["gst calculator", "gst calculator india", "add gst", "remove gst", "reverse gst calculator"],
    component: "gst-calculator",
    volumeEstimate: 301000,
    howTo: [
      "Enter the amount.",
      "Choose whether to add GST (amount is exclusive) or remove GST (amount is inclusive).",
      "Pick the GST rate.",
      "See the GST amount, total, and CGST/SGST breakdown.",
    ],
    faqs: [
      { q: "How do I remove GST from a total price?", a: "Base amount = total ÷ (1 + rate/100). For example, to remove 18% GST from ₹1,180: 1180 ÷ 1.18 = ₹1,000 base, so GST is ₹180. Switch the tool to 'Remove GST' to do this automatically." },
      { q: "What is the CGST and SGST split?", a: "For intra-state sales, GST is split equally into CGST and SGST. At 18%, that's 9% CGST + 9% SGST. The calculator shows this split for you." },
      { q: "Which GST rate should I use?", a: "Most goods and services now fall in the 5% or 18% slab after the September 2025 rate rationalisation; a 40% rate applies to demerit goods like tobacco, pan masala and luxury cars. Check your item's HSN/SAC code to confirm." },
    ],
    related: ["emi-calculator", "sip-calculator"],
  },
  {
    slug: "compound-interest-calculator",
    category: "finance",
    name: "Compound Interest Calculator",
    h1: "Compound Interest Calculator",
    tagline: "See how your money grows with compound interest over time.",
    title: "Compound Interest Calculator — Free Online Tool",
    description:
      "Free compound interest calculator. Find the maturity value and interest earned for any principal, rate, time and compounding frequency. Instant results.",
    intro:
      "Calculate how an investment grows with compound interest. Enter your principal, annual rate, time and compounding frequency (annually, quarterly, monthly) to see the maturity value and total interest earned.",
    keywords: ["compound interest calculator", "compound interest formula", "ci calculator", "interest calculator"],
    component: "compound-interest",
    volumeEstimate: 673000,
    howTo: ["Enter principal, rate and time.", "Choose how often interest compounds.", "Read the maturity value and interest earned."],
    faqs: [
      { q: "What is the compound interest formula?", a: "A = P(1 + r/n)^(nt), where P is principal, r is the annual rate (decimal), n is compounding periods per year, and t is years. Interest = A − P." },
      { q: "Does more frequent compounding earn more?", a: "Yes — monthly compounding earns slightly more than annual at the same rate, because interest starts earning interest sooner." },
    ],
    related: ["simple-interest-calculator", "fd-calculator", "sip-calculator"],
  },
  {
    slug: "simple-interest-calculator",
    category: "finance",
    name: "Simple Interest Calculator",
    h1: "Simple Interest Calculator",
    tagline: "Calculate simple interest and total amount in seconds.",
    title: "Simple Interest Calculator — Free Online SI Tool",
    description:
      "Free simple interest calculator. Compute simple interest and the total amount for any principal, rate and time using the SI = P×R×T/100 formula.",
    intro:
      "Calculate simple interest on a principal over a period of time. Enter the principal, annual rate and number of years to see the interest and the total amount payable.",
    keywords: ["simple interest calculator", "simple interest formula", "si calculator", "interest calculator"],
    component: "simple-interest",
    volumeEstimate: 49500,
    howTo: ["Enter principal, rate and time in years.", "Read the simple interest and total amount.", "Adjust any value to compare."],
    faqs: [
      { q: "What is the simple interest formula?", a: "Simple Interest = (P × R × T) / 100, where P is principal, R is the annual rate, and T is time in years. The total amount is P + interest." },
      { q: "How is simple interest different from compound?", a: "Simple interest is calculated only on the original principal; compound interest is calculated on the principal plus accumulated interest, so it grows faster." },
    ],
    related: ["compound-interest-calculator", "emi-calculator", "fd-calculator"],
  },
  {
    slug: "fd-calculator",
    category: "finance",
    name: "FD Calculator",
    h1: "FD Calculator (Fixed Deposit)",
    tagline: "Estimate your fixed deposit maturity value and interest.",
    title: "FD Calculator — Fixed Deposit Maturity Calculator (India)",
    description:
      "Free FD calculator. Estimate the maturity value and interest on a fixed deposit with quarterly (or other) compounding. Fast and accurate for India.",
    intro:
      "Estimate the maturity value of a fixed deposit (FD). Enter your deposit amount, interest rate and tenure — FDs in India typically compound quarterly, which is the default here.",
    keywords: ["fd calculator", "fixed deposit calculator", "fd maturity calculator", "fd interest calculator"],
    component: "fd-calculator",
    volumeEstimate: 450000,
    howTo: ["Enter the deposit amount, rate and tenure.", "Keep quarterly compounding (FD standard) or change it.", "See the maturity value and interest."],
    faqs: [
      { q: "How is FD interest calculated?", a: "Most banks compound FD interest quarterly: A = P(1 + r/4)^(4t). This calculator defaults to quarterly to match that convention." },
      { q: "Is FD interest taxable?", a: "Yes, FD interest is taxable as per your income slab in India, and banks may deduct TDS. This calculator shows the pre-tax maturity value." },
    ],
    related: ["compound-interest-calculator", "sip-calculator", "emi-calculator"],
  },
  {
    slug: "percentage-calculator",
    category: "finance",
    name: "Percentage Calculator",
    h1: "Percentage Calculator",
    tagline: "Work out percentages, ratios and percentage change.",
    title: "Percentage Calculator — Free Online % Tool",
    description:
      "Free percentage calculator. Find X% of a number, what percent one number is of another, and the percentage increase or decrease between two values.",
    intro:
      "A three-in-one percentage calculator: find X% of a value, work out what percent one number is of another, and calculate the percentage increase or decrease between two numbers.",
    keywords: ["percentage calculator", "percent calculator", "percentage change calculator", "what percent of"],
    component: "percentage-calculator",
    volumeEstimate: 450000,
    howTo: ["Pick the calculation you need.", "Enter the two numbers.", "Read the answer instantly."],
    faqs: [
      { q: "How do I find what percent one number is of another?", a: "Divide the part by the whole and multiply by 100. For example, 50 of 200 is (50 ÷ 200) × 100 = 25%." },
      { q: "How is percentage change calculated?", a: "Percentage change = ((new − old) / old) × 100. A positive result is an increase; a negative result is a decrease." },
    ],
    related: ["discount-calculator", "gst-calculator", "simple-interest-calculator"],
  },
  {
    slug: "discount-calculator",
    category: "finance",
    name: "Discount Calculator",
    h1: "Discount Calculator",
    tagline: "Find the sale price and how much you save on a discount.",
    title: "Discount Calculator — Free Online Sale Price Tool",
    description:
      "Free discount calculator. Enter an original price and discount percentage to instantly see how much you save and the final sale price.",
    intro:
      "Quickly work out a sale price. Enter the original price and the discount percentage to see how much you save and what you'll actually pay.",
    keywords: ["discount calculator", "sale price calculator", "percent off calculator", "how much do i save"],
    component: "discount-calculator",
    volumeEstimate: 40500,
    howTo: ["Enter the original price.", "Enter the discount percentage.", "Read your savings and the final price."],
    faqs: [
      { q: "How do I calculate a discount?", a: "Multiply the price by the discount percentage and divide by 100 to get the amount saved, then subtract that from the price. E.g. 25% off ₹2,000 saves ₹500, so you pay ₹1,500." },
      { q: "Can I work out the percentage off from two prices?", a: "Use the Percentage Calculator's 'percentage change' mode with the original and sale price to find the discount percent." },
    ],
    related: ["percentage-calculator", "gst-calculator", "emi-calculator"],
  },
  {
    slug: "gratuity-calculator",
    category: "finance",
    name: "Gratuity Calculator",
    h1: "Gratuity Calculator (India)",
    tagline: "Calculate your gratuity with the 15/26 formula in seconds.",
    title: "Gratuity Calculator — Calculate Gratuity Online (India)",
    description:
      "Free gratuity calculator for India. Uses the 15/26 formula on your last drawn basic + DA and years of service, with the ₹20 lakh cap applied automatically.",
    intro:
      "Estimate the gratuity payable when you leave a job after long service. Enter your last drawn monthly salary (basic + DA) and completed years of service — the calculator applies the Payment of Gratuity Act formula and the statutory ₹20 lakh ceiling.",
    keywords: ["gratuity calculator", "gratuity calculation formula", "gratuity amount calculator", "15/26 gratuity formula"],
    component: "gratuity-calculator",
    volumeEstimate: 301000,
    howTo: [
      "Enter your last drawn monthly basic salary plus dearness allowance.",
      "Enter your completed years of service.",
      "Read the gratuity payable — the ₹20 lakh statutory cap is applied automatically.",
    ],
    faqs: [
      { q: "What is the gratuity formula?", a: "Gratuity = (15 ÷ 26) × last drawn monthly salary (basic + DA) × completed years of service. 15/26 represents 15 days' wages out of a 26-working-day month, per year served." },
      { q: "Who is eligible for gratuity?", a: "Employees who complete 5 continuous years with the same employer (the 5-year condition is waived in case of death or disablement). Service beyond 6 months in the final year rounds up to a full year." },
      { q: "Is there a maximum gratuity amount?", a: "Yes — ₹20 lakh under the Payment of Gratuity Act. Employers can pay more voluntarily, but the excess has different tax treatment." },
    ],
    related: ["hra-calculator", "fd-calculator", "sip-calculator"],
  },
  {
    slug: "hra-calculator",
    category: "finance",
    name: "HRA Calculator",
    h1: "HRA Exemption Calculator",
    tagline: "Find how much of your HRA is tax-exempt with the 3-rule test.",
    title: "HRA Calculator — House Rent Allowance Exemption (India)",
    description:
      "Free HRA exemption calculator. Applies the least-of-three rule (actual HRA, rent minus 10% of basic, 50%/40% of basic) to show exempt and taxable HRA instantly.",
    intro:
      "Work out how much of your House Rent Allowance escapes income tax. The exemption is the least of three amounts — actual HRA received, rent paid minus 10% of basic, and 50% (metro) or 40% (non-metro) of basic salary. This calculator shows all three and the binding one.",
    keywords: ["hra calculator", "hra exemption calculator", "house rent allowance calculation", "hra tax exemption"],
    component: "hra-calculator",
    volumeEstimate: 27100,
    howTo: [
      "Enter your monthly basic + DA, the HRA you receive, and the rent you pay.",
      "Pick metro or non-metro city.",
      "Read the exempt and taxable HRA per month and per year.",
    ],
    faqs: [
      { q: "How is HRA exemption calculated?", a: "It is the least of: (1) actual HRA received, (2) rent paid minus 10% of basic + DA, and (3) 50% of basic + DA in a metro (40% elsewhere). Whatever remains of your HRA is taxable." },
      { q: "Does HRA exemption work under the new tax regime?", a: "No — HRA exemption is available only under the old tax regime. Under the new regime, HRA is fully taxable, which is one factor when choosing between regimes." },
      { q: "Which cities count as metro for HRA?", a: "Delhi, Mumbai, Kolkata and Chennai qualify for the 50% limit; all other cities use 40%." },
    ],
    related: ["gratuity-calculator", "percentage-calculator", "emi-calculator"],
  },
  {
    slug: "inflation-calculator",
    category: "finance",
    name: "Inflation Calculator",
    h1: "Inflation Calculator",
    tagline: "See what today's money will be worth — and cost — in the future.",
    title: "Inflation Calculator — Future Cost & Purchasing Power",
    description:
      "Free inflation calculator. See the future cost of today's expenses and how much purchasing power your money loses over time at any inflation rate.",
    intro:
      "Inflation quietly reprices everything. Enter an amount, an assumed inflation rate and a time horizon to see what today's expense will cost in the future — and how much today's money will actually buy by then.",
    keywords: ["inflation calculator", "future value of money", "purchasing power calculator", "inflation rate calculator india"],
    component: "inflation-calculator",
    volumeEstimate: 550000,
    howTo: [
      "Enter an amount in today's rupees.",
      "Set an inflation assumption (India's CPI has often run around 5–6%).",
      "Read the future cost and the future buying power of the same amount.",
    ],
    faqs: [
      { q: "How is the future cost calculated?", a: "Future cost = amount × (1 + inflation rate)^years. At 6% inflation, ₹1,00,000 of expenses today costs about ₹1,79,000 in 10 years." },
      { q: "What inflation rate should I assume for India?", a: "Long-run consumer inflation in India has often averaged around 5–6%, but it varies by period and by category (education and healthcare typically run higher). Test a range." },
      { q: "Why does this matter for investing?", a: "Returns below inflation lose purchasing power even though the number grows. Subtracting inflation from your expected return gives the 'real' return that actually compounds your wealth." },
    ],
    related: ["sip-calculator", "lumpsum-calculator", "fd-calculator"],
  },
  {
    slug: "lumpsum-calculator",
    category: "finance",
    name: "Lumpsum Calculator",
    h1: "Lumpsum Investment Calculator",
    tagline: "Project the future value of a one-time investment.",
    title: "Lumpsum Calculator — One-Time Investment Returns",
    description:
      "Free lumpsum calculator. Project the maturity value and gains of a one-time mutual fund or other investment at any expected return and duration.",
    intro:
      "Estimate how a one-time investment grows with compounding. Enter the amount, an expected annual return and the holding period to see the projected maturity value and total gains.",
    keywords: ["lumpsum calculator", "lump sum investment calculator", "one time investment calculator", "mutual fund lumpsum calculator"],
    component: "lumpsum-calculator",
    volumeEstimate: 165000,
    howTo: [
      "Enter your one-time investment amount.",
      "Set the expected annual return and duration.",
      "Read the projected maturity value and gains.",
    ],
    faqs: [
      { q: "How is lumpsum maturity calculated?", a: "Future value = amount × (1 + r)^n, where r is the annual return and n the years. ₹1 lakh at 12% for 10 years grows to about ₹3.1 lakh." },
      { q: "Lumpsum or SIP — which is better?", a: "Lumpsum puts all your money to work immediately, which wins when markets rise steadily; SIP spreads entries and reduces timing risk. See our SIP vs lumpsum guide for the full comparison." },
      { q: "Are the projected returns guaranteed?", a: "No — market returns vary year to year. The calculator assumes a constant rate, so treat the output as a planning estimate." },
    ],
    related: ["sip-calculator", "cagr-calculator", "compound-interest-calculator"],
  },
  {
    slug: "cagr-calculator",
    category: "finance",
    name: "CAGR Calculator",
    h1: "CAGR Calculator",
    tagline: "Find the compound annual growth rate between two values.",
    title: "CAGR Calculator — Compound Annual Growth Rate Online",
    description:
      "Free CAGR calculator. Enter a starting value, ending value and years to get the compound annual growth rate, plus the absolute return for comparison.",
    intro:
      "CAGR (compound annual growth rate) converts any growth between two points in time into a steady per-year rate — the cleanest way to compare investments held for different durations.",
    keywords: ["cagr calculator", "cagr formula", "compound annual growth rate", "cagr calculation online"],
    component: "cagr-calculator",
    volumeEstimate: 60500,
    howTo: [
      "Enter the initial value of the investment.",
      "Enter the final value and the years held.",
      "Read the CAGR and the absolute return.",
    ],
    faqs: [
      { q: "What is the CAGR formula?", a: "CAGR = (final ÷ initial)^(1 ÷ years) − 1. Growing ₹1,00,000 to ₹2,50,000 over 5 years is a CAGR of about 20.1% per year." },
      { q: "Why use CAGR instead of absolute return?", a: "A 150% absolute return sounds great until you learn it took 15 years (≈6.3% CAGR). CAGR normalises for time, letting you compare investments fairly." },
      { q: "Can CAGR be negative?", a: "Yes — if the final value is below the initial value, CAGR is negative, representing the steady annual rate of loss." },
    ],
    related: ["lumpsum-calculator", "sip-calculator", "compound-interest-calculator"],
  },
  {
    slug: "swp-calculator",
    category: "finance",
    name: "SWP Calculator",
    h1: "SWP Calculator",
    tagline: "Plan monthly withdrawals — and see how long your corpus lasts.",
    title: "SWP Calculator — Systematic Withdrawal Plan (India)",
    description:
      "Free SWP calculator. See how long your corpus lasts with monthly withdrawals, the total you withdraw and what remains, at any expected return.",
    intro:
      "A Systematic Withdrawal Plan (SWP) pays you a fixed amount every month from an invested corpus while the balance keeps earning. Enter your corpus, monthly withdrawal, expected return and period — if the withdrawals outpace growth, the calculator shows exactly how long the money lasts.",
    keywords: ["swp calculator", "systematic withdrawal plan calculator", "swp calculator india", "monthly withdrawal calculator"],
    component: "swp-calculator",
    volumeEstimate: 450000,
    howTo: [
      "Enter your starting corpus and desired monthly withdrawal.",
      "Set the expected annual return and the withdrawal period.",
      "Read the remaining corpus — or how long the money lasts if it depletes.",
    ],
    faqs: [
      { q: "What is an SWP?", a: "The reverse of a SIP: instead of investing monthly, you redeem a fixed amount monthly from a mutual fund corpus, commonly used for retirement income." },
      { q: "How do I make a corpus last forever?", a: "Keep the monthly withdrawal at or below the corpus's monthly growth: roughly corpus × annual return ÷ 12. Withdraw more than that and the principal starts depleting." },
      { q: "Is SWP better than a fixed deposit for monthly income?", a: "SWP from a fund offers market-linked growth and potentially better post-tax outcomes, but the corpus can fall in bad markets; an FD's payout is fixed and predictable. Many retirees blend both." },
    ],
    related: ["sip-calculator", "fd-calculator", "lumpsum-calculator"],
  },
  {
    slug: "income-tax-calculator",
    category: "finance",
    name: "Income Tax Calculator",
    h1: "Income Tax Calculator (New Regime, FY 2025-26)",
    tagline: "Calculate your income tax under India's new regime instantly.",
    title: "Income Tax Calculator — New Regime FY 2025-26 (India)",
    description:
      "Free income tax calculator for India's new regime, FY 2025-26: latest slabs, ₹75,000 standard deduction, §87A rebate up to ₹12 lakh and 4% cess applied automatically.",
    intro:
      "Estimate your income tax for FY 2025-26 (AY 2026-27) under the new tax regime — the default for most taxpayers. The calculator applies the latest slabs, the ₹75,000 standard deduction for salaried income, the §87A rebate (zero tax up to ₹12 lakh taxable) with marginal relief, and the 4% health and education cess.",
    keywords: ["income tax calculator", "income tax calculator india", "new regime tax calculator", "tax calculator fy 2025-26"],
    component: "income-tax-calculator",
    volumeEstimate: 201000,
    updated: "2026-06-09",
    updateNote: "FY 2025-26 new-regime slabs",
    howTo: [
      "Enter your annual income.",
      "Choose salaried (applies the ₹75,000 standard deduction) or other income.",
      "Read your taxable income, total tax with cess, effective rate and approximate monthly TDS.",
    ],
    faqs: [
      { q: "What are the new regime slabs for FY 2025-26?", a: "0% up to ₹4L; 5% on ₹4–8L; 10% on ₹8–12L; 15% on ₹12–16L; 20% on ₹16–20L; 25% on ₹20–24L; 30% above ₹24L — plus 4% cess on the tax." },
      { q: "Is income up to ₹12 lakh really tax-free?", a: "Yes for taxable income up to ₹12L: the §87A rebate cancels the slab tax for resident individuals, and salaried taxpayers effectively get up to ₹12.75L tax-free thanks to the ₹75,000 standard deduction. Marginal relief smooths the cliff just above ₹12L." },
      { q: "Does this calculator cover the old regime?", a: "No — it models the new (default) regime only. If you claim large deductions like 80C, HRA and home-loan interest, compare with the old regime before filing." },
    ],
    related: ["salary-calculator", "hra-calculator", "gratuity-calculator"],
  },
  {
    slug: "salary-calculator",
    category: "finance",
    name: "Salary Calculator",
    h1: "In-Hand Salary Calculator (CTC to Take-Home)",
    tagline: "Convert your CTC into the monthly amount that actually arrives.",
    title: "Salary Calculator — CTC to In-Hand Salary (India)",
    description:
      "Free in-hand salary calculator for India. Convert annual CTC to monthly take-home after PF, income tax (new regime FY 2025-26) and professional tax.",
    intro:
      "CTC and take-home are very different numbers. This calculator converts your annual CTC into the monthly in-hand amount after employer and employee PF, income tax under the new regime (FY 2025-26), and professional tax — with each deduction shown.",
    keywords: ["salary calculator", "in hand salary calculator", "ctc to in hand salary", "take home salary calculator"],
    component: "salary-calculator",
    volumeEstimate: 246000,
    updated: "2026-06-09",
    updateNote: "FY 2025-26 new-regime rules",
    howTo: [
      "Enter your annual CTC and your basic salary percentage (40–50% is typical).",
      "Keep 'employer PF in CTC' checked if your offer letter counts it in CTC (most do).",
      "Read your monthly in-hand, annual tax and PF deductions.",
    ],
    faqs: [
      { q: "Why is my in-hand salary so much lower than CTC?", a: "CTC includes things you never see monthly: the employer's PF contribution, gratuity provision and sometimes insurance or bonuses. Income tax and your own PF contribution then come out of the rest." },
      { q: "What percentage of CTC is basic salary?", a: "Commonly 40–50%. A higher basic raises PF (forced savings and lower in-hand) and HRA; a lower basic does the reverse. Your offer letter's salary structure has the exact split." },
      { q: "Which tax regime does this use?", a: "The new regime for FY 2025-26 with the ₹75,000 standard deduction — the default for most salaried taxpayers. Old-regime deductions like 80C and HRA exemption are not modelled." },
    ],
    related: ["income-tax-calculator", "hra-calculator", "gratuity-calculator"],
  },
  {
    slug: "ppf-calculator",
    category: "finance",
    name: "PPF Calculator",
    h1: "PPF Calculator",
    tagline: "Project your Public Provident Fund maturity, tax-free.",
    title: "PPF Calculator — Public Provident Fund Maturity (India)",
    description:
      "Free PPF calculator. Project your Public Provident Fund maturity value and tax-free interest for yearly deposits over 15+ years at the current rate.",
    intro:
      "The PPF is India's favourite guaranteed, tax-free savings scheme: deposit up to ₹1.5 lakh a year, earn a government-set rate (recently around 7.1%), and everything — deposits, interest, maturity — is tax-exempt. Project your corpus here.",
    keywords: ["ppf calculator", "ppf maturity calculator", "public provident fund calculator", "ppf interest calculator"],
    component: "ppf-calculator",
    volumeEstimate: 246000,
    howTo: [
      "Enter your yearly deposit (₹1,50,000 is the annual cap).",
      "Keep the current interest rate or adjust it.",
      "Set the duration (minimum 15 years) and read the maturity value.",
    ],
    faqs: [
      { q: "What is the PPF interest rate?", a: "The government resets it quarterly; it has hovered around 7.1% in recent years. Interest is compounded annually and credited each March 31." },
      { q: "Is PPF interest taxable?", a: "No — PPF enjoys EEE status: the deposit qualifies for 80C (old regime), and both interest and maturity are completely tax-free." },
      { q: "Can I withdraw before 15 years?", a: "Partial withdrawals are allowed from year 7, and loans against the balance from year 3. Full withdrawal needs the 15-year maturity, after which you can extend in 5-year blocks." },
    ],
    related: ["fd-calculator", "nps-calculator", "sip-calculator"],
  },
  {
    slug: "rd-calculator",
    category: "finance",
    name: "RD Calculator",
    h1: "RD Calculator (Recurring Deposit)",
    tagline: "Calculate recurring deposit maturity with quarterly compounding.",
    title: "RD Calculator — Recurring Deposit Maturity (India)",
    description:
      "Free RD calculator. Find your recurring deposit maturity value and interest with bank-standard quarterly compounding for any monthly deposit and tenure.",
    intro:
      "A recurring deposit is a fixed-deposit habit: a set amount every month at a guaranteed rate. Enter your monthly deposit, rate and tenure to see the maturity value, computed with the quarterly compounding banks actually use.",
    keywords: ["rd calculator", "recurring deposit calculator", "rd maturity calculator", "rd interest calculator"],
    component: "rd-calculator",
    volumeEstimate: 201000,
    howTo: [
      "Enter your monthly deposit amount.",
      "Set the bank's RD interest rate and the tenure.",
      "Read the maturity value and total interest.",
    ],
    faqs: [
      { q: "How is RD interest calculated?", a: "Indian banks compound RD balances quarterly. Each instalment earns from the month it lands, so this calculator simulates the account month by month with quarterly compounding." },
      { q: "Is RD interest taxable?", a: "Yes — it is added to your income and taxed at slab rate, and banks deduct TDS if interest crosses the threshold. The PPF and ELSS are alternatives with tax advantages." },
      { q: "RD or SIP — which should I pick?", a: "RD gives a guaranteed, slab-taxed return — good for short-term goals. SIPs are market-linked with higher long-term potential and better tax treatment. Match the instrument to the goal's horizon." },
    ],
    related: ["fd-calculator", "ppf-calculator", "sip-calculator"],
  },
  {
    slug: "nps-calculator",
    category: "finance",
    name: "NPS Calculator",
    h1: "NPS Calculator",
    tagline: "Project your retirement corpus and pension under NPS.",
    title: "NPS Calculator — National Pension System Corpus (India)",
    description:
      "Free NPS calculator. Project your National Pension System retirement corpus from monthly contributions, with the 60% lump sum and 40% annuity split shown.",
    intro:
      "The National Pension System compounds your monthly contributions until retirement, then lets you withdraw up to 60% tax-free while at least 40% buys an annuity for monthly pension. Project your corpus and that split here.",
    keywords: ["nps calculator", "national pension system calculator", "nps returns calculator", "nps pension calculator"],
    component: "nps-calculator",
    volumeEstimate: 135000,
    howTo: [
      "Enter your monthly NPS contribution and expected return (NPS funds mix equity and debt).",
      "Set your current and retirement age.",
      "Read the projected corpus, the 60% lump sum and the 40% annuity portion.",
    ],
    faqs: [
      { q: "How much pension will NPS give me?", a: "At retirement, at least 40% of the corpus must buy an annuity; your monthly pension is that annuity's payout (rates vary by insurer, roughly 6–7% of the annuity corpus per year currently)." },
      { q: "What return should I assume for NPS?", a: "NPS funds blend equity (E), corporate debt (C) and government bonds (G). Balanced allocations have historically delivered high single digits to around 10% — adjust to your own mix." },
      { q: "Is NPS withdrawal tax-free?", a: "The 60% lump sum at retirement is tax-free. The annuity portion's monthly pension is taxable as income in the year received." },
    ],
    related: ["ppf-calculator", "sip-calculator", "gratuity-calculator"],
  },
  {
    slug: "home-loan-emi-calculator",
    category: "finance",
    name: "Home Loan EMI Calculator",
    h1: "Home Loan EMI Calculator",
    tagline: "Calculate your housing loan EMI, interest and total cost.",
    title: "Home Loan EMI Calculator — Housing Loan EMI (India)",
    description:
      "Free home loan EMI calculator. Find your monthly housing loan EMI, total interest and total repayment for any amount, rate and tenure up to 30 years.",
    intro:
      "Home loans are the biggest EMI most people ever pay, and small rate differences compound into lakhs. Enter your loan amount, interest rate and tenure to see the monthly EMI, total interest and total repayment — preset with typical home-loan figures.",
    keywords: ["home loan emi calculator", "housing loan emi calculator", "home loan calculator india", "home loan interest calculator"],
    component: "emi-calculator",
    params: { principal: 3000000, rate: 8.5, years: 20 },
    volumeEstimate: 673000,
    howTo: [
      "Enter the loan amount you plan to borrow.",
      "Set the interest rate your bank quoted and the tenure (15–30 years is common).",
      "Read the monthly EMI, total interest and total amount payable.",
    ],
    faqs: [
      { q: "How is a home loan EMI calculated?", a: "With the reducing-balance formula EMI = P × r × (1+r)^n ÷ ((1+r)^n − 1). A ₹30 lakh loan at 8.5% for 20 years works out to roughly ₹26,000 a month." },
      { q: "Should I pick a longer tenure for a lower EMI?", a: "A longer tenure eases the monthly burden but sharply raises total interest — on ₹30L at 8.5%, going from 20 to 30 years adds several lakh in interest. Prepay when you can to claw it back." },
      { q: "Do home loans have prepayment charges?", a: "Floating-rate home loans to individuals cannot carry prepayment penalties under RBI rules — prepaying early in the tenure is the single biggest interest saver." },
    ],
    related: ["emi-calculator", "car-loan-emi-calculator", "income-tax-calculator"],
  },
  {
    slug: "car-loan-emi-calculator",
    category: "finance",
    name: "Car Loan EMI Calculator",
    h1: "Car Loan EMI Calculator",
    tagline: "Work out your car loan EMI before you visit the showroom.",
    title: "Car Loan EMI Calculator — Auto Loan EMI (India)",
    description:
      "Free car loan EMI calculator. Find your monthly car loan EMI, total interest and total cost for any amount, rate and tenure — before the dealer does.",
    intro:
      "Know your EMI before the showroom does the math for you. Enter the loan amount, rate and tenure to see the monthly EMI and the true total cost of financing the car — preset with typical car-loan figures.",
    keywords: ["car loan emi calculator", "car loan calculator", "auto loan emi calculator", "vehicle loan emi"],
    component: "emi-calculator",
    params: { principal: 800000, rate: 9.5, years: 7 },
    volumeEstimate: 301000,
    howTo: [
      "Enter the amount you plan to finance (price minus down payment).",
      "Set the interest rate and tenure (3–7 years is typical).",
      "Read the monthly EMI and the total interest you'd pay.",
    ],
    faqs: [
      { q: "What tenure is best for a car loan?", a: "Shorter is cheaper: cars depreciate while interest accrues, so a 3–5 year loan keeps total interest down and avoids owing more than the car is worth." },
      { q: "Why is my dealer's 'flat rate' quote misleading?", a: "Dealers often quote flat rates, which charge interest on the full original amount throughout. A 6% flat rate costs about the same as an 11% reducing-balance rate — always compare EMIs, not quoted rates." },
      { q: "Should I make a bigger down payment?", a: "Usually yes: financing less of a depreciating asset saves interest outright and lowers the EMI. Keep an emergency buffer though — don't drain savings entirely for the down payment." },
    ],
    related: ["emi-calculator", "home-loan-emi-calculator", "discount-calculator"],
  },
  {
    slug: "tip-calculator",
    category: "finance",
    name: "Tip Calculator",
    h1: "Tip Calculator",
    tagline: "Work out the tip and split the bill between any number of people.",
    title: "Tip Calculator — Free Online Bill & Gratuity Splitter",
    description:
      "Free tip calculator. Enter the bill, choose a tip percentage, and split the total between any number of people. See tip, total and per-person amounts instantly.",
    intro:
      "Enter your bill amount, pick a tip percentage (or drag the slider), and choose how many people are splitting. You instantly get the tip, the grand total, and the amount each person owes — perfect for restaurants, cafes and group outings. Everything calculates live in your browser.",
    keywords: ["tip calculator", "gratuity calculator", "bill split calculator", "how much to tip"],
    component: "tip-calculator",
    volumeEstimate: 450000,
    howTo: [
      "Enter the bill amount.",
      "Choose a tip percentage with the buttons or slider.",
      "Set how many people are splitting the bill.",
      "Read the tip, total and per-person amounts.",
    ],
    faqs: [
      { q: "What is a standard tip percentage?", a: "In the US, 15–20% is typical for table service, with 18% a common default. Norms vary by country and service type, so adjust to your situation." },
      { q: "Is the tip calculated before or after tax?", a: "This calculator applies the tip percentage to the amount you enter. If you prefer to tip on the pre-tax subtotal, enter that figure as the bill." },
    ],
    related: ["discount-calculator", "percentage-calculator", "gst-calculator"],
  },
  {
    slug: "gpa-calculator",
    category: "finance",
    name: "GPA Calculator",
    h1: "GPA Calculator",
    tagline: "Calculate your grade point average on the 4.0 scale, weighted by credits.",
    title: "GPA Calculator — Free Online Grade Point Average Tool",
    description:
      "Free GPA calculator. Add your courses, letter grades and credit hours to get your weighted grade point average on the standard 4.0 scale. Instant, private.",
    intro:
      "Add each course with its letter grade and credit hours to compute your weighted GPA on the standard US 4.0 scale. Add or remove courses as needed; the average and total credits update instantly. Calculations run entirely in your browser — nothing is saved or uploaded.",
    keywords: ["gpa calculator", "grade point average calculator", "college gpa calculator", "weighted gpa calculator"],
    component: "gpa-calculator",
    volumeEstimate: 823000,
    howTo: [
      "Enter each course name, its letter grade and its credit hours.",
      "Add more courses with the Add course button.",
      "Read your weighted GPA on the 4.0 scale.",
    ],
    faqs: [
      { q: "How is GPA calculated?", a: "Each grade maps to grade points (A=4.0, B=3.0…). Multiply each course's points by its credits, sum them, and divide by total credits to get the credit-weighted average." },
      { q: "What grade scale does this use?", a: "The standard US 4.0 scale with +/− grades (A=4.0, A−=3.7, B+=3.3, and so on down to F=0.0)." },
    ],
    related: ["percentage-calculator", "tip-calculator"],
  },
  {
    slug: "step-up-sip-calculator",
    category: "finance",
    name: "Step Up SIP Calculator",
    h1: "Step Up SIP Calculator",
    tagline: "Project your SIP's maturity value when you increase it every year.",
    title: "Step Up SIP Calculator — Annual Top-Up SIP Returns",
    description:
      "Free step up SIP calculator. See how increasing your SIP by 5–15% every year grows your corpus, with a year-by-year table of invested amount and value.",
    intro:
      "A step-up (top-up) SIP increases your monthly investment by a fixed percentage every year, matching your salary increments. Enter your starting SIP, annual step-up, expected return and period to see the maturity value — and open the year-by-year table to watch the compounding accelerate. A 10% annual step-up typically grows the final corpus by 45–80% versus a flat SIP over 15+ years.",
    keywords: ["step up sip calculator", "top up sip calculator", "sip step up", "increasing sip calculator"],
    component: "step-up-sip-calculator",
    volumeEstimate: 135000,
    updated: "2026-06-13",
    howTo: [
      "Enter your starting monthly SIP amount.",
      "Set the annual step-up percentage (10% is a common default, matching salary growth).",
      "Enter the expected annual return and investment period.",
      "Read the maturity value, and open the year-by-year table to see the growth path.",
    ],
    faqs: [
      { q: "What is a step-up SIP?", a: "A SIP where the monthly contribution automatically increases by a fixed percentage every year — for example ₹10,000 growing 10% annually becomes ₹11,000 in year 2, ₹12,100 in year 3, and so on. Most fund platforms let you set this up once." },
      { q: "How much difference does a step-up make?", a: "A lot over long periods. Because the larger contributions also compound, a 10% annual step-up over 15–20 years typically produces 45–80% more corpus than keeping the SIP flat." },
      { q: "What step-up percentage should I choose?", a: "Match it to your realistic salary growth — 5–10% is common. The key is consistency: a modest step-up you sustain beats an aggressive one you cancel." },
    ],
    related: ["sip-calculator", "lumpsum-calculator", "swp-calculator"],
  },
  {
    slug: "ssy-calculator",
    category: "finance",
    name: "Sukanya Samriddhi Yojana Calculator",
    h1: "Sukanya Samriddhi Yojana (SSY) Calculator",
    tagline: "Calculate the maturity value of your daughter's SSY account.",
    title: "SSY Calculator — Sukanya Samriddhi Yojana Maturity Value",
    description:
      "Free Sukanya Samriddhi Yojana calculator. Enter your yearly deposit to see the maturity value at 21 years with the current 8.2% government rate. Updated quarterly.",
    intro:
      "Sukanya Samriddhi Yojana is a government-backed savings scheme for a girl child, offering one of the highest small-savings interest rates with full tax exemption (EEE). Deposits run for the first 15 years; the account matures 21 years after opening. Enter your planned yearly deposit (₹250 to ₹1.5 lakh) to project the maturity amount at the current rate.",
    keywords: ["sukanya samriddhi yojana calculator", "ssy calculator", "sukanya samriddhi calculator", "ssy maturity calculator"],
    component: "ssy-calculator",
    volumeEstimate: 110000,
    updated: "2026-06-13",
    updateNote: "8.2% rate (FY 2025-26)",
    howTo: [
      "Enter the amount you plan to deposit each year (₹250 – ₹1,50,000).",
      "Check the interest rate — we pre-fill the current government rate.",
      "Read the total deposited, interest earned and the maturity value at 21 years.",
    ],
    faqs: [
      { q: "How long do I deposit, and when does SSY mature?", a: "You deposit for the first 15 years from account opening; the account then keeps earning interest and matures 21 years after opening (or on the girl's marriage after she turns 18)." },
      { q: "Is SSY interest taxable?", a: "No. SSY has EEE status — the deposit qualifies under Section 80C, and both the interest and the maturity amount are fully tax-free." },
      { q: "Does the interest rate change?", a: "Yes. The government reviews small-savings rates every quarter. The rate is 8.2% as of FY 2025-26; your actual maturity value will reflect the rates declared over the years." },
    ],
    related: ["ppf-calculator", "fd-calculator", "rd-calculator"],
  },
  {
    slug: "epf-calculator",
    category: "finance",
    name: "EPF Calculator",
    h1: "EPF Calculator — Provident Fund Corpus at Retirement",
    tagline: "Project your Employees' Provident Fund balance at retirement.",
    title: "EPF Calculator — PF Corpus & Interest at Retirement",
    description:
      "Free EPF calculator. Project your provident fund corpus at retirement from your basic salary, with employee + employer contributions and 8.25% EPFO interest.",
    intro:
      "Estimate your EPF corpus at retirement from your monthly basic salary (plus DA). The calculator applies the statutory split — your 12%, plus the employer's 12% minus the 8.33% EPS diversion on wages up to ₹15,000 — and compounds the EPFO-declared interest monthly, with your salary growing annually. Open your payslip, copy the basic, and see where you'll land at 58.",
    keywords: ["epf calculator", "pf calculator", "provident fund calculator", "epf corpus calculator"],
    component: "epf-calculator",
    volumeEstimate: 27100,
    updated: "2026-06-13",
    updateNote: "8.25% EPFO rate (FY 2024-25)",
    howTo: [
      "Enter your current monthly basic salary + dearness allowance.",
      "Set your current age, retirement age and expected annual salary growth.",
      "Check the EPF interest rate (pre-filled with the latest EPFO declaration).",
      "Read your projected corpus, total contributions and interest earned.",
    ],
    faqs: [
      { q: "How much goes into EPF each month?", a: "You contribute 12% of basic+DA. Your employer also pays 12%, but 8.33% of wages (capped at a ₹15,000 wage base) is diverted to the pension scheme (EPS) — the rest joins your EPF balance." },
      { q: "What interest rate does EPF pay?", a: "EPFO declares the rate yearly — 8.25% for FY 2024-25. Interest is calculated on monthly running balances and credited annually, and it's tax-free within the contribution limits." },
      { q: "Can I withdraw EPF before retirement?", a: "Partial withdrawals are allowed for specific purposes (home purchase, medical, education) after minimum service periods, and the full balance after 2 months of unemployment — but early withdrawals sacrifice the most powerful compounding years." },
    ],
    related: ["nps-calculator", "ppf-calculator", "gratuity-calculator", "salary-calculator"],
  },
  {
    slug: "fire-calculator",
    category: "finance",
    name: "FIRE Calculator",
    h1: "FIRE Calculator — Financial Independence, Retire Early",
    tagline: "Find your FIRE number and how many years until you reach it.",
    title: "FIRE Calculator — Your Financial Independence Number",
    description:
      "Free FIRE calculator. Get your financial independence number from annual expenses and the 4% rule, and see how many years your savings rate needs to reach it.",
    intro:
      "FIRE (Financial Independence, Retire Early) reduces to one number: the portfolio that lets you withdraw your annual expenses indefinitely. With the classic 4% safe withdrawal rate, that's 25× your yearly spending. Enter your expenses, current savings, monthly investment and expected return to get your FIRE number and a realistic countdown to reaching it.",
    keywords: ["fire calculator", "financial independence calculator", "retire early calculator", "fire number"],
    component: "fire-calculator",
    volumeEstimate: 18100,
    updated: "2026-06-13",
    howTo: [
      "Enter your annual living expenses (what retirement actually costs you, not your income).",
      "Set a safe withdrawal rate — 4% is the classic baseline; 3–3.5% is more conservative.",
      "Enter current savings, your monthly investment and expected return.",
      "Read your FIRE number and the projected years to reach it.",
    ],
    faqs: [
      { q: "What is the 4% rule?", a: "A guideline from the Trinity study: withdrawing 4% of a diversified portfolio in year one (inflation-adjusted after) historically survived 30-year retirements. It implies needing 25× annual expenses; conservative planners use 3–3.5% (28–33×)." },
      { q: "Should I use pre-tax or post-tax expenses?", a: "Use your real annual spending including taxes you'll pay on withdrawals. Underestimating expenses is the most common FIRE planning error." },
      { q: "Does this account for inflation?", a: "Use a real (inflation-adjusted) return — e.g. 7% nominal minus 3% inflation ≈ 4% real — and the result reads in today's money, which is the honest way to plan." },
    ],
    related: ["net-worth-calculator", "swp-calculator", "sip-calculator", "compound-interest-calculator"],
  },
  {
    slug: "net-worth-calculator",
    category: "finance",
    name: "Net Worth Calculator",
    h1: "Net Worth Calculator",
    tagline: "Add what you own, subtract what you owe — your true financial position.",
    title: "Net Worth Calculator — Assets Minus Liabilities",
    description:
      "Free net worth calculator. Total your assets (cash, investments, property) and liabilities (loans, credit cards) to see your net worth instantly. Private, in-browser.",
    intro:
      "Net worth is the single clearest measure of financial health: everything you own minus everything you owe. Fill in your assets and liabilities — nothing you type leaves your browser — and track the number over time. Growing net worth (not income) is what financial progress actually looks like.",
    keywords: ["net worth calculator", "calculate net worth", "assets minus liabilities", "net worth tracker"],
    component: "net-worth-calculator",
    volumeEstimate: 27100,
    updated: "2026-06-13",
    howTo: [
      "Enter your assets: cash, investments, retirement accounts, property, vehicles.",
      "Enter your liabilities: loan balances, credit card debt, other debts.",
      "Read your net worth — and recheck it quarterly to track the trend.",
    ],
    faqs: [
      { q: "Should I include my home and car?", a: "Yes — at realistic resale value, with the loan balances under liabilities. Some people track a separate 'liquid net worth' that excludes the primary home, since you can't spend it without moving." },
      { q: "Is a negative net worth bad?", a: "It's common early on (student loans, new mortgage). What matters is the direction: paying down debt and investing both move the number up — track it quarterly rather than judging a single snapshot." },
      { q: "Is my financial data stored anywhere?", a: "No. Everything computes locally in your browser and disappears when you close the tab." },
    ],
    related: ["fire-calculator", "emergency-fund-calculator", "emi-calculator"],
  },
  {
    slug: "emergency-fund-calculator",
    category: "finance",
    name: "Emergency Fund Calculator",
    h1: "Emergency Fund Calculator",
    tagline: "How much you should keep aside, and how long until you're covered.",
    title: "Emergency Fund Calculator — How Much Should You Save?",
    description:
      "Free emergency fund calculator. Get your target fund from monthly expenses (3–12 months of cover), see how funded you are, and how fast you can close the gap.",
    intro:
      "An emergency fund is 3–12 months of essential expenses in instantly-accessible savings — the buffer that keeps a job loss or medical bill from becoming debt. Enter your essential monthly spending, pick a cover level, and see your target, how much of it you already have, and how many months of saving will close the gap.",
    keywords: ["emergency fund calculator", "emergency savings calculator", "how much emergency fund", "rainy day fund calculator"],
    component: "emergency-fund-calculator",
    volumeEstimate: 9900,
    updated: "2026-06-13",
    howTo: [
      "Enter your essential monthly expenses (rent, food, utilities, EMIs, insurance).",
      "Choose months of cover — 6 months is the standard recommendation.",
      "Enter your current emergency savings and monthly saving capacity.",
      "Read your target, your funded percentage and your time to goal.",
    ],
    faqs: [
      { q: "How many months should my emergency fund cover?", a: "6 months of essential expenses is the common target. Use 3 months if you have very stable income and low obligations; 9–12 if you're self-employed, single-income or in a volatile industry." },
      { q: "Where should I keep the emergency fund?", a: "Somewhere safe and instantly accessible — a high-yield savings account or sweep-in FD. Not equities: the fund's job is availability in a crisis, not returns." },
      { q: "Do I count only essential expenses?", a: "Yes — what you'd actually spend in a tight month (housing, food, utilities, insurance, loan payments), not your full lifestyle spending. That keeps the target honest and reachable." },
    ],
    related: ["net-worth-calculator", "fd-calculator", "rd-calculator"],
  },
  {
    slug: "percentage-increase-calculator",
    category: "finance",
    name: "Percentage Increase Calculator",
    h1: "Percentage Increase Calculator",
    tagline: "Find the percent change between two numbers — increase or decrease.",
    title: "Percentage Increase Calculator — Percent Change Between Two Numbers",
    description:
      "Free percentage increase calculator. Enter an initial and final value to get the percent increase or decrease and the absolute change, with the formula shown.",
    intro:
      "Enter where a number started and where it ended to get the percentage change — positive for an increase, negative for a decrease — along with the absolute difference and the exact formula used. Handy for price changes, salary hikes, traffic growth and test scores.",
    keywords: ["percentage increase calculator", "percent change calculator", "percentage difference", "percent increase formula"],
    component: "percentage-increase-calculator",
    volumeEstimate: 165000,
    updated: "2026-06-13",
    howTo: [
      "Enter the initial value.",
      "Enter the final value.",
      "Read the percentage change, the absolute change, and the worked formula.",
    ],
    faqs: [
      { q: "What is the percentage increase formula?", a: "(final − initial) ÷ |initial| × 100. For example, going from 80 to 100 is (100 − 80) ÷ 80 × 100 = +25%." },
      { q: "Why can't the initial value be zero?", a: "Percentage change measures growth relative to the starting point — with a starting point of zero, any change is infinite, so the result is mathematically undefined." },
      { q: "Is percentage increase the same as percentage difference?", a: "No. Percentage change is directional (from initial to final); percentage difference compares two values symmetrically against their average. This tool computes directional change, which is what most people mean." },
    ],
    related: ["percentage-calculator", "discount-calculator", "cagr-calculator"],
  },
];
