import type { Tool } from "../types";

export const financeTools: Tool[] = [
  {
    slug: "emi-calculator",
    category: "finance",
    name: "EMI Calculator",
    h1: "EMI Calculator",
    tagline: "Calculate your monthly loan EMI, total interest and total payment.",
    title: "EMI Calculator — Free Online Loan EMI Calculator (India)",
    description:
      "Free EMI calculator. Find your monthly loan EMI, total interest and total payable for home, car or personal loans. Instant, accurate, mobile-friendly.",
    intro:
      "Work out the Equated Monthly Instalment (EMI) for any loan — home, car, personal or business. Enter the loan amount, annual interest rate and tenure to see your monthly EMI, the total interest you'll pay, and the total amount payable over the loan.",
    keywords: ["emi calculator", "loan emi calculator", "home loan emi", "car loan emi calculator"],
    component: "emi-calculator",
    volumeEstimate: 2740000,
    howTo: [
      "Enter the loan (principal) amount.",
      "Enter the annual interest rate (%).",
      "Enter the tenure in months or years.",
      "See your monthly EMI, total interest and total payment update instantly.",
    ],
    faqs: [
      { q: "How is EMI calculated?", a: "EMI = P × r × (1+r)^n / ((1+r)^n − 1), where P is the principal, r is the monthly interest rate (annual rate ÷ 12 ÷ 100), and n is the number of monthly instalments." },
      { q: "Does a longer tenure reduce my EMI?", a: "Yes — a longer tenure lowers the monthly EMI, but you pay more total interest over the life of the loan. The calculator shows that trade-off clearly." },
      { q: "Is this EMI calculator accurate for home loans?", a: "Yes. The reducing-balance formula it uses is the standard method banks apply for home, car and personal loans on a fixed interest rate." },
    ],
    related: ["sip-calculator", "gst-calculator"],
  },
  {
    slug: "sip-calculator",
    category: "finance",
    name: "SIP Calculator",
    h1: "SIP Calculator",
    tagline: "Estimate the future value of your monthly mutual fund SIP.",
    title: "SIP Calculator — Free Mutual Fund SIP Returns Calculator",
    description:
      "Free SIP calculator. Estimate the maturity value and total returns of your monthly mutual fund SIP based on amount, tenure and expected return.",
    intro:
      "See how a monthly Systematic Investment Plan (SIP) could grow. Enter your monthly investment, the expected annual return and the duration to estimate the maturity value, the total amount you invested, and the wealth gained through compounding.",
    keywords: ["sip calculator", "mutual fund sip calculator", "sip return calculator", "sip maturity calculator"],
    component: "sip-calculator",
    volumeEstimate: 3350000,
    howTo: [
      "Enter your monthly SIP amount.",
      "Enter the expected annual return (%).",
      "Enter the investment duration in years.",
      "See the estimated maturity value and total gains instantly.",
    ],
    faqs: [
      { q: "How does a SIP calculator work?", a: "It applies the future-value-of-a-series formula: M = P × [((1+i)^n − 1) / i] × (1+i), where P is the monthly amount, i is the monthly return (annual ÷ 12 ÷ 100), and n is the number of months." },
      { q: "Are the returns guaranteed?", a: "No. Mutual fund returns are market-linked and vary. The calculator uses an assumed constant rate to project an estimate — actual results will differ." },
      { q: "What return rate should I assume?", a: "Many investors model equity SIPs at around 10–12% per year for long-term planning, but this is only an assumption — adjust it to your own expectations." },
    ],
    related: ["emi-calculator", "gst-calculator"],
  },
  {
    slug: "gst-calculator",
    category: "finance",
    name: "GST Calculator",
    h1: "GST Calculator (India)",
    tagline: "Add or remove GST at 5%, 18% or any other slab in seconds.",
    title: "GST Calculator — Add or Remove GST Online (India)",
    description:
      "Free GST calculator for India. Add GST to a base price or remove GST from an inclusive price at 5%, 18% or other slabs. See CGST/SGST split instantly.",
    intro:
      "Calculate GST both ways: add GST to a net amount to get the gross price, or remove GST from a GST-inclusive price to find the base amount. Pick a rate — 5% and 18% are the main slabs since the September 2025 rationalisation, with legacy 12%/28% and the 40% demerit rate also supported — and see the GST amount, the total, and the CGST/SGST split.",
    keywords: ["gst calculator", "gst calculator india", "add gst", "remove gst", "reverse gst calculator"],
    component: "gst-calculator",
    volumeEstimate: 301000,
    howTo: [
      "Enter the amount.",
      "Choose whether to add GST (amount is exclusive) or remove GST (amount is inclusive).",
      "Pick the GST rate.",
      "See the GST amount, total, and CGST/SGST breakdown.",
    ],
    faqs: [
      { q: "How do I remove GST from a total price?", a: "Base amount = total ÷ (1 + rate/100). For example, to remove 18% GST from ₹1,180: 1180 ÷ 1.18 = ₹1,000 base, so GST is ₹180. Switch the tool to 'Remove GST' to do this automatically." },
      { q: "What is the CGST and SGST split?", a: "For intra-state sales, GST is split equally into CGST and SGST. At 18%, that's 9% CGST + 9% SGST. The calculator shows this split for you." },
      { q: "Which GST rate should I use?", a: "Most goods and services now fall in the 5% or 18% slab after the September 2025 rate rationalisation; a 40% rate applies to demerit goods like tobacco, pan masala and luxury cars. Check your item's HSN/SAC code to confirm." },
    ],
    related: ["emi-calculator", "sip-calculator"],
  },
  {
    slug: "compound-interest-calculator",
    category: "finance",
    name: "Compound Interest Calculator",
    h1: "Compound Interest Calculator",
    tagline: "See how your money grows with compound interest over time.",
    title: "Compound Interest Calculator — Free Online Tool",
    description:
      "Free compound interest calculator. Find the maturity value and interest earned for any principal, rate, time and compounding frequency. Instant results.",
    intro:
      "Calculate how an investment grows with compound interest. Enter your principal, annual rate, time and compounding frequency (annually, quarterly, monthly) to see the maturity value and total interest earned.",
    keywords: ["compound interest calculator", "compound interest formula", "ci calculator", "interest calculator"],
    component: "compound-interest",
    volumeEstimate: 673000,
    howTo: ["Enter principal, rate and time.", "Choose how often interest compounds.", "Read the maturity value and interest earned."],
    faqs: [
      { q: "What is the compound interest formula?", a: "A = P(1 + r/n)^(nt), where P is principal, r is the annual rate (decimal), n is compounding periods per year, and t is years. Interest = A − P." },
      { q: "Does more frequent compounding earn more?", a: "Yes — monthly compounding earns slightly more than annual at the same rate, because interest starts earning interest sooner." },
    ],
    related: ["simple-interest-calculator", "fd-calculator", "sip-calculator"],
  },
  {
    slug: "simple-interest-calculator",
    category: "finance",
    name: "Simple Interest Calculator",
    h1: "Simple Interest Calculator",
    tagline: "Calculate simple interest and total amount in seconds.",
    title: "Simple Interest Calculator — Free Online SI Tool",
    description:
      "Free simple interest calculator. Compute simple interest and the total amount for any principal, rate and time using the SI = P×R×T/100 formula.",
    intro:
      "Calculate simple interest on a principal over a period of time. Enter the principal, annual rate and number of years to see the interest and the total amount payable.",
    keywords: ["simple interest calculator", "simple interest formula", "si calculator", "interest calculator"],
    component: "simple-interest",
    volumeEstimate: 49500,
    howTo: ["Enter principal, rate and time in years.", "Read the simple interest and total amount.", "Adjust any value to compare."],
    faqs: [
      { q: "What is the simple interest formula?", a: "Simple Interest = (P × R × T) / 100, where P is principal, R is the annual rate, and T is time in years. The total amount is P + interest." },
      { q: "How is simple interest different from compound?", a: "Simple interest is calculated only on the original principal; compound interest is calculated on the principal plus accumulated interest, so it grows faster." },
    ],
    related: ["compound-interest-calculator", "emi-calculator", "fd-calculator"],
  },
  {
    slug: "fd-calculator",
    category: "finance",
    name: "FD Calculator",
    h1: "FD Calculator (Fixed Deposit)",
    tagline: "Estimate your fixed deposit maturity value and interest.",
    title: "FD Calculator — Fixed Deposit Maturity Calculator (India)",
    description:
      "Free FD calculator. Estimate the maturity value and interest on a fixed deposit with quarterly (or other) compounding. Fast and accurate for India.",
    intro:
      "Estimate the maturity value of a fixed deposit (FD). Enter your deposit amount, interest rate and tenure — FDs in India typically compound quarterly, which is the default here.",
    keywords: ["fd calculator", "fixed deposit calculator", "fd maturity calculator", "fd interest calculator"],
    component: "fd-calculator",
    volumeEstimate: 450000,
    howTo: ["Enter the deposit amount, rate and tenure.", "Keep quarterly compounding (FD standard) or change it.", "See the maturity value and interest."],
    faqs: [
      { q: "How is FD interest calculated?", a: "Most banks compound FD interest quarterly: A = P(1 + r/4)^(4t). This calculator defaults to quarterly to match that convention." },
      { q: "Is FD interest taxable?", a: "Yes, FD interest is taxable as per your income slab in India, and banks may deduct TDS. This calculator shows the pre-tax maturity value." },
    ],
    related: ["compound-interest-calculator", "sip-calculator", "emi-calculator"],
  },
  {
    slug: "percentage-calculator",
    category: "finance",
    name: "Percentage Calculator",
    h1: "Percentage Calculator",
    tagline: "Work out percentages, ratios and percentage change.",
    title: "Percentage Calculator — Free Online % Tool",
    description:
      "Free percentage calculator. Find X% of a number, what percent one number is of another, and the percentage increase or decrease between two values.",
    intro:
      "A three-in-one percentage calculator: find X% of a value, work out what percent one number is of another, and calculate the percentage increase or decrease between two numbers.",
    keywords: ["percentage calculator", "percent calculator", "percentage change calculator", "what percent of"],
    component: "percentage-calculator",
    volumeEstimate: 450000,
    howTo: ["Pick the calculation you need.", "Enter the two numbers.", "Read the answer instantly."],
    faqs: [
      { q: "How do I find what percent one number is of another?", a: "Divide the part by the whole and multiply by 100. For example, 50 of 200 is (50 ÷ 200) × 100 = 25%." },
      { q: "How is percentage change calculated?", a: "Percentage change = ((new − old) / old) × 100. A positive result is an increase; a negative result is a decrease." },
    ],
    related: ["discount-calculator", "gst-calculator", "simple-interest-calculator"],
  },
  {
    slug: "discount-calculator",
    category: "finance",
    name: "Discount Calculator",
    h1: "Discount Calculator",
    tagline: "Find the sale price and how much you save on a discount.",
    title: "Discount Calculator — Free Online Sale Price Tool",
    description:
      "Free discount calculator. Enter an original price and discount percentage to instantly see how much you save and the final sale price.",
    intro:
      "Quickly work out a sale price. Enter the original price and the discount percentage to see how much you save and what you'll actually pay.",
    keywords: ["discount calculator", "sale price calculator", "percent off calculator", "how much do i save"],
    component: "discount-calculator",
    volumeEstimate: 40500,
    howTo: ["Enter the original price.", "Enter the discount percentage.", "Read your savings and the final price."],
    faqs: [
      { q: "How do I calculate a discount?", a: "Multiply the price by the discount percentage and divide by 100 to get the amount saved, then subtract that from the price. E.g. 25% off ₹2,000 saves ₹500, so you pay ₹1,500." },
      { q: "Can I work out the percentage off from two prices?", a: "Use the Percentage Calculator's 'percentage change' mode with the original and sale price to find the discount percent." },
    ],
    related: ["percentage-calculator", "gst-calculator", "emi-calculator"],
  },
  {
    slug: "gratuity-calculator",
    category: "finance",
    name: "Gratuity Calculator",
    h1: "Gratuity Calculator (India)",
    tagline: "Calculate your gratuity with the 15/26 formula in seconds.",
    title: "Gratuity Calculator — Calculate Gratuity Online (India)",
    description:
      "Free gratuity calculator for India. Uses the 15/26 formula on your last drawn basic + DA and years of service, with the ₹20 lakh cap applied automatically.",
    intro:
      "Estimate the gratuity payable when you leave a job after long service. Enter your last drawn monthly salary (basic + DA) and completed years of service — the calculator applies the Payment of Gratuity Act formula and the statutory ₹20 lakh ceiling.",
    keywords: ["gratuity calculator", "gratuity calculation formula", "gratuity amount calculator", "15/26 gratuity formula"],
    component: "gratuity-calculator",
    volumeEstimate: 301000,
    howTo: [
      "Enter your last drawn monthly basic salary plus dearness allowance.",
      "Enter your completed years of service.",
      "Read the gratuity payable — the ₹20 lakh statutory cap is applied automatically.",
    ],
    faqs: [
      { q: "What is the gratuity formula?", a: "Gratuity = (15 ÷ 26) × last drawn monthly salary (basic + DA) × completed years of service. 15/26 represents 15 days' wages out of a 26-working-day month, per year served." },
      { q: "Who is eligible for gratuity?", a: "Employees who complete 5 continuous years with the same employer (the 5-year condition is waived in case of death or disablement). Service beyond 6 months in the final year rounds up to a full year." },
      { q: "Is there a maximum gratuity amount?", a: "Yes — ₹20 lakh under the Payment of Gratuity Act. Employers can pay more voluntarily, but the excess has different tax treatment." },
    ],
    related: ["hra-calculator", "fd-calculator", "sip-calculator"],
  },
  {
    slug: "hra-calculator",
    category: "finance",
    name: "HRA Calculator",
    h1: "HRA Exemption Calculator",
    tagline: "Find how much of your HRA is tax-exempt with the 3-rule test.",
    title: "HRA Calculator — House Rent Allowance Exemption (India)",
    description:
      "Free HRA exemption calculator. Applies the least-of-three rule (actual HRA, rent minus 10% of basic, 50%/40% of basic) to show exempt and taxable HRA instantly.",
    intro:
      "Work out how much of your House Rent Allowance escapes income tax. The exemption is the least of three amounts — actual HRA received, rent paid minus 10% of basic, and 50% (metro) or 40% (non-metro) of basic salary. This calculator shows all three and the binding one.",
    keywords: ["hra calculator", "hra exemption calculator", "house rent allowance calculation", "hra tax exemption"],
    component: "hra-calculator",
    volumeEstimate: 27100,
    howTo: [
      "Enter your monthly basic + DA, the HRA you receive, and the rent you pay.",
      "Pick metro or non-metro city.",
      "Read the exempt and taxable HRA per month and per year.",
    ],
    faqs: [
      { q: "How is HRA exemption calculated?", a: "It is the least of: (1) actual HRA received, (2) rent paid minus 10% of basic + DA, and (3) 50% of basic + DA in a metro (40% elsewhere). Whatever remains of your HRA is taxable." },
      { q: "Does HRA exemption work under the new tax regime?", a: "No — HRA exemption is available only under the old tax regime. Under the new regime, HRA is fully taxable, which is one factor when choosing between regimes." },
      { q: "Which cities count as metro for HRA?", a: "Delhi, Mumbai, Kolkata and Chennai qualify for the 50% limit; all other cities use 40%." },
    ],
    related: ["gratuity-calculator", "percentage-calculator", "emi-calculator"],
  },
  {
    slug: "inflation-calculator",
    category: "finance",
    name: "Inflation Calculator",
    h1: "Inflation Calculator",
    tagline: "See what today's money will be worth — and cost — in the future.",
    title: "Inflation Calculator — Future Cost & Purchasing Power",
    description:
      "Free inflation calculator. See the future cost of today's expenses and how much purchasing power your money loses over time at any inflation rate.",
    intro:
      "Inflation quietly reprices everything. Enter an amount, an assumed inflation rate and a time horizon to see what today's expense will cost in the future — and how much today's money will actually buy by then.",
    keywords: ["inflation calculator", "future value of money", "purchasing power calculator", "inflation rate calculator india"],
    component: "inflation-calculator",
    volumeEstimate: 550000,
    howTo: [
      "Enter an amount in today's rupees.",
      "Set an inflation assumption (India's CPI has often run around 5–6%).",
      "Read the future cost and the future buying power of the same amount.",
    ],
    faqs: [
      { q: "How is the future cost calculated?", a: "Future cost = amount × (1 + inflation rate)^years. At 6% inflation, ₹1,00,000 of expenses today costs about ₹1,79,000 in 10 years." },
      { q: "What inflation rate should I assume for India?", a: "Long-run consumer inflation in India has often averaged around 5–6%, but it varies by period and by category (education and healthcare typically run higher). Test a range." },
      { q: "Why does this matter for investing?", a: "Returns below inflation lose purchasing power even though the number grows. Subtracting inflation from your expected return gives the 'real' return that actually compounds your wealth." },
    ],
    related: ["sip-calculator", "lumpsum-calculator", "fd-calculator"],
  },
  {
    slug: "lumpsum-calculator",
    category: "finance",
    name: "Lumpsum Calculator",
    h1: "Lumpsum Investment Calculator",
    tagline: "Project the future value of a one-time investment.",
    title: "Lumpsum Calculator — One-Time Investment Returns",
    description:
      "Free lumpsum calculator. Project the maturity value and gains of a one-time mutual fund or other investment at any expected return and duration.",
    intro:
      "Estimate how a one-time investment grows with compounding. Enter the amount, an expected annual return and the holding period to see the projected maturity value and total gains.",
    keywords: ["lumpsum calculator", "lump sum investment calculator", "one time investment calculator", "mutual fund lumpsum calculator"],
    component: "lumpsum-calculator",
    volumeEstimate: 165000,
    howTo: [
      "Enter your one-time investment amount.",
      "Set the expected annual return and duration.",
      "Read the projected maturity value and gains.",
    ],
    faqs: [
      { q: "How is lumpsum maturity calculated?", a: "Future value = amount × (1 + r)^n, where r is the annual return and n the years. ₹1 lakh at 12% for 10 years grows to about ₹3.1 lakh." },
      { q: "Lumpsum or SIP — which is better?", a: "Lumpsum puts all your money to work immediately, which wins when markets rise steadily; SIP spreads entries and reduces timing risk. See our SIP vs lumpsum guide for the full comparison." },
      { q: "Are the projected returns guaranteed?", a: "No — market returns vary year to year. The calculator assumes a constant rate, so treat the output as a planning estimate." },
    ],
    related: ["sip-calculator", "cagr-calculator", "compound-interest-calculator"],
  },
  {
    slug: "cagr-calculator",
    category: "finance",
    name: "CAGR Calculator",
    h1: "CAGR Calculator",
    tagline: "Find the compound annual growth rate between two values.",
    title: "CAGR Calculator — Compound Annual Growth Rate Online",
    description:
      "Free CAGR calculator. Enter a starting value, ending value and years to get the compound annual growth rate, plus the absolute return for comparison.",
    intro:
      "CAGR (compound annual growth rate) converts any growth between two points in time into a steady per-year rate — the cleanest way to compare investments held for different durations.",
    keywords: ["cagr calculator", "cagr formula", "compound annual growth rate", "cagr calculation online"],
    component: "cagr-calculator",
    volumeEstimate: 60500,
    howTo: [
      "Enter the initial value of the investment.",
      "Enter the final value and the years held.",
      "Read the CAGR and the absolute return.",
    ],
    faqs: [
      { q: "What is the CAGR formula?", a: "CAGR = (final ÷ initial)^(1 ÷ years) − 1. Growing ₹1,00,000 to ₹2,50,000 over 5 years is a CAGR of about 20.1% per year." },
      { q: "Why use CAGR instead of absolute return?", a: "A 150% absolute return sounds great until you learn it took 15 years (≈6.3% CAGR). CAGR normalises for time, letting you compare investments fairly." },
      { q: "Can CAGR be negative?", a: "Yes — if the final value is below the initial value, CAGR is negative, representing the steady annual rate of loss." },
    ],
    related: ["lumpsum-calculator", "sip-calculator", "compound-interest-calculator"],
  },
  {
    slug: "swp-calculator",
    category: "finance",
    name: "SWP Calculator",
    h1: "SWP Calculator",
    tagline: "Plan monthly withdrawals — and see how long your corpus lasts.",
    title: "SWP Calculator — Systematic Withdrawal Plan (India)",
    description:
      "Free SWP calculator. See how long your corpus lasts with monthly withdrawals, the total you withdraw and what remains, at any expected return.",
    intro:
      "A Systematic Withdrawal Plan (SWP) pays you a fixed amount every month from an invested corpus while the balance keeps earning. Enter your corpus, monthly withdrawal, expected return and period — if the withdrawals outpace growth, the calculator shows exactly how long the money lasts.",
    keywords: ["swp calculator", "systematic withdrawal plan calculator", "swp calculator india", "monthly withdrawal calculator"],
    component: "swp-calculator",
    volumeEstimate: 450000,
    howTo: [
      "Enter your starting corpus and desired monthly withdrawal.",
      "Set the expected annual return and the withdrawal period.",
      "Read the remaining corpus — or how long the money lasts if it depletes.",
    ],
    faqs: [
      { q: "What is an SWP?", a: "The reverse of a SIP: instead of investing monthly, you redeem a fixed amount monthly from a mutual fund corpus, commonly used for retirement income." },
      { q: "How do I make a corpus last forever?", a: "Keep the monthly withdrawal at or below the corpus's monthly growth: roughly corpus × annual return ÷ 12. Withdraw more than that and the principal starts depleting." },
      { q: "Is SWP better than a fixed deposit for monthly income?", a: "SWP from a fund offers market-linked growth and potentially better post-tax outcomes, but the corpus can fall in bad markets; an FD's payout is fixed and predictable. Many retirees blend both." },
    ],
    related: ["sip-calculator", "fd-calculator", "lumpsum-calculator"],
  },
  {
    slug: "income-tax-calculator",
    category: "finance",
    name: "Income Tax Calculator",
    h1: "Income Tax Calculator (New Regime, FY 2025-26)",
    tagline: "Calculate your income tax under India's new regime instantly.",
    title: "Income Tax Calculator — New Regime FY 2025-26 (India)",
    description:
      "Free income tax calculator for India's new regime, FY 2025-26: latest slabs, ₹75,000 standard deduction, §87A rebate up to ₹12 lakh and 4% cess applied automatically.",
    intro:
      "Estimate your income tax for FY 2025-26 (AY 2026-27) under the new tax regime — the default for most taxpayers. The calculator applies the latest slabs, the ₹75,000 standard deduction for salaried income, the §87A rebate (zero tax up to ₹12 lakh taxable) with marginal relief, and the 4% health and education cess.",
    keywords: ["income tax calculator", "income tax calculator india", "new regime tax calculator", "tax calculator fy 2025-26"],
    component: "income-tax-calculator",
    volumeEstimate: 201000,
    updated: "2026-06-09",
    updateNote: "FY 2025-26 new-regime slabs",
    howTo: [
      "Enter your annual income.",
      "Choose salaried (applies the ₹75,000 standard deduction) or other income.",
      "Read your taxable income, total tax with cess, effective rate and approximate monthly TDS.",
    ],
    faqs: [
      { q: "What are the new regime slabs for FY 2025-26?", a: "0% up to ₹4L; 5% on ₹4–8L; 10% on ₹8–12L; 15% on ₹12–16L; 20% on ₹16–20L; 25% on ₹20–24L; 30% above ₹24L — plus 4% cess on the tax." },
      { q: "Is income up to ₹12 lakh really tax-free?", a: "Yes for taxable income up to ₹12L: the §87A rebate cancels the slab tax for resident individuals, and salaried taxpayers effectively get up to ₹12.75L tax-free thanks to the ₹75,000 standard deduction. Marginal relief smooths the cliff just above ₹12L." },
      { q: "Does this calculator cover the old regime?", a: "No — it models the new (default) regime only. If you claim large deductions like 80C, HRA and home-loan interest, compare with the old regime before filing." },
    ],
    related: ["salary-calculator", "hra-calculator", "gratuity-calculator"],
  },
  {
    slug: "salary-calculator",
    category: "finance",
    name: "Salary Calculator",
    h1: "In-Hand Salary Calculator (CTC to Take-Home)",
    tagline: "Convert your CTC into the monthly amount that actually arrives.",
    title: "Salary Calculator — CTC to In-Hand Salary (India)",
    description:
      "Free in-hand salary calculator for India. Convert annual CTC to monthly take-home after PF, income tax (new regime FY 2025-26) and professional tax.",
    intro:
      "CTC and take-home are very different numbers. This calculator converts your annual CTC into the monthly in-hand amount after employer and employee PF, income tax under the new regime (FY 2025-26), and professional tax — with each deduction shown.",
    keywords: ["salary calculator", "in hand salary calculator", "ctc to in hand salary", "take home salary calculator"],
    component: "salary-calculator",
    volumeEstimate: 246000,
    updated: "2026-06-09",
    updateNote: "FY 2025-26 new-regime rules",
    howTo: [
      "Enter your annual CTC and your basic salary percentage (40–50% is typical).",
      "Keep 'employer PF in CTC' checked if your offer letter counts it in CTC (most do).",
      "Read your monthly in-hand, annual tax and PF deductions.",
    ],
    faqs: [
      { q: "Why is my in-hand salary so much lower than CTC?", a: "CTC includes things you never see monthly: the employer's PF contribution, gratuity provision and sometimes insurance or bonuses. Income tax and your own PF contribution then come out of the rest." },
      { q: "What percentage of CTC is basic salary?", a: "Commonly 40–50%. A higher basic raises PF (forced savings and lower in-hand) and HRA; a lower basic does the reverse. Your offer letter's salary structure has the exact split." },
      { q: "Which tax regime does this use?", a: "The new regime for FY 2025-26 with the ₹75,000 standard deduction — the default for most salaried taxpayers. Old-regime deductions like 80C and HRA exemption are not modelled." },
    ],
    related: ["income-tax-calculator", "hra-calculator", "gratuity-calculator"],
  },
  {
    slug: "ppf-calculator",
    category: "finance",
    name: "PPF Calculator",
    h1: "PPF Calculator",
    tagline: "Project your Public Provident Fund maturity, tax-free.",
    title: "PPF Calculator — Public Provident Fund Maturity (India)",
    description:
      "Free PPF calculator. Project your Public Provident Fund maturity value and tax-free interest for yearly deposits over 15+ years at the current rate.",
    intro:
      "The PPF is India's favourite guaranteed, tax-free savings scheme: deposit up to ₹1.5 lakh a year, earn a government-set rate (recently around 7.1%), and everything — deposits, interest, maturity — is tax-exempt. Project your corpus here.",
    keywords: ["ppf calculator", "ppf maturity calculator", "public provident fund calculator", "ppf interest calculator"],
    component: "ppf-calculator",
    volumeEstimate: 246000,
    howTo: [
      "Enter your yearly deposit (₹1,50,000 is the annual cap).",
      "Keep the current interest rate or adjust it.",
      "Set the duration (minimum 15 years) and read the maturity value.",
    ],
    faqs: [
      { q: "What is the PPF interest rate?", a: "The government resets it quarterly; it has hovered around 7.1% in recent years. Interest is compounded annually and credited each March 31." },
      { q: "Is PPF interest taxable?", a: "No — PPF enjoys EEE status: the deposit qualifies for 80C (old regime), and both interest and maturity are completely tax-free." },
      { q: "Can I withdraw before 15 years?", a: "Partial withdrawals are allowed from year 7, and loans against the balance from year 3. Full withdrawal needs the 15-year maturity, after which you can extend in 5-year blocks." },
    ],
    related: ["fd-calculator", "nps-calculator", "sip-calculator"],
  },
  {
    slug: "rd-calculator",
    category: "finance",
    name: "RD Calculator",
    h1: "RD Calculator (Recurring Deposit)",
    tagline: "Calculate recurring deposit maturity with quarterly compounding.",
    title: "RD Calculator — Recurring Deposit Maturity (India)",
    description:
      "Free RD calculator. Find your recurring deposit maturity value and interest with bank-standard quarterly compounding for any monthly deposit and tenure.",
    intro:
      "A recurring deposit is a fixed-deposit habit: a set amount every month at a guaranteed rate. Enter your monthly deposit, rate and tenure to see the maturity value, computed with the quarterly compounding banks actually use.",
    keywords: ["rd calculator", "recurring deposit calculator", "rd maturity calculator", "rd interest calculator"],
    component: "rd-calculator",
    volumeEstimate: 201000,
    howTo: [
      "Enter your monthly deposit amount.",
      "Set the bank's RD interest rate and the tenure.",
      "Read the maturity value and total interest.",
    ],
    faqs: [
      { q: "How is RD interest calculated?", a: "Indian banks compound RD balances quarterly. Each instalment earns from the month it lands, so this calculator simulates the account month by month with quarterly compounding." },
      { q: "Is RD interest taxable?", a: "Yes — it is added to your income and taxed at slab rate, and banks deduct TDS if interest crosses the threshold. The PPF and ELSS are alternatives with tax advantages." },
      { q: "RD or SIP — which should I pick?", a: "RD gives a guaranteed, slab-taxed return — good for short-term goals. SIPs are market-linked with higher long-term potential and better tax treatment. Match the instrument to the goal's horizon." },
    ],
    related: ["fd-calculator", "ppf-calculator", "sip-calculator"],
  },
  {
    slug: "nps-calculator",
    category: "finance",
    name: "NPS Calculator",
    h1: "NPS Calculator",
    tagline: "Project your retirement corpus and pension under NPS.",
    title: "NPS Calculator — National Pension System Corpus (India)",
    description:
      "Free NPS calculator. Project your National Pension System retirement corpus from monthly contributions, with the 60% lump sum and 40% annuity split shown.",
    intro:
      "The National Pension System compounds your monthly contributions until retirement, then lets you withdraw up to 60% tax-free while at least 40% buys an annuity for monthly pension. Project your corpus and that split here.",
    keywords: ["nps calculator", "national pension system calculator", "nps returns calculator", "nps pension calculator"],
    component: "nps-calculator",
    volumeEstimate: 135000,
    howTo: [
      "Enter your monthly NPS contribution and expected return (NPS funds mix equity and debt).",
      "Set your current and retirement age.",
      "Read the projected corpus, the 60% lump sum and the 40% annuity portion.",
    ],
    faqs: [
      { q: "How much pension will NPS give me?", a: "At retirement, at least 40% of the corpus must buy an annuity; your monthly pension is that annuity's payout (rates vary by insurer, roughly 6–7% of the annuity corpus per year currently)." },
      { q: "What return should I assume for NPS?", a: "NPS funds blend equity (E), corporate debt (C) and government bonds (G). Balanced allocations have historically delivered high single digits to around 10% — adjust to your own mix." },
      { q: "Is NPS withdrawal tax-free?", a: "The 60% lump sum at retirement is tax-free. The annuity portion's monthly pension is taxable as income in the year received." },
    ],
    related: ["ppf-calculator", "sip-calculator", "gratuity-calculator"],
  },
  {
    slug: "home-loan-emi-calculator",
    category: "finance",
    name: "Home Loan EMI Calculator",
    h1: "Home Loan EMI Calculator",
    tagline: "Calculate your housing loan EMI, interest and total cost.",
    title: "Home Loan EMI Calculator — Housing Loan EMI (India)",
    description:
      "Free home loan EMI calculator. Find your monthly housing loan EMI, total interest and total repayment for any amount, rate and tenure up to 30 years.",
    intro:
      "Home loans are the biggest EMI most people ever pay, and small rate differences compound into lakhs. Enter your loan amount, interest rate and tenure to see the monthly EMI, total interest and total repayment — preset with typical home-loan figures.",
    keywords: ["home loan emi calculator", "housing loan emi calculator", "home loan calculator india", "home loan interest calculator"],
    component: "emi-calculator",
    params: { principal: 3000000, rate: 8.5, years: 20 },
    volumeEstimate: 673000,
    howTo: [
      "Enter the loan amount you plan to borrow.",
      "Set the interest rate your bank quoted and the tenure (15–30 years is common).",
      "Read the monthly EMI, total interest and total amount payable.",
    ],
    faqs: [
      { q: "How is a home loan EMI calculated?", a: "With the reducing-balance formula EMI = P × r × (1+r)^n ÷ ((1+r)^n − 1). A ₹30 lakh loan at 8.5% for 20 years works out to roughly ₹26,000 a month." },
      { q: "Should I pick a longer tenure for a lower EMI?", a: "A longer tenure eases the monthly burden but sharply raises total interest — on ₹30L at 8.5%, going from 20 to 30 years adds several lakh in interest. Prepay when you can to claw it back." },
      { q: "Do home loans have prepayment charges?", a: "Floating-rate home loans to individuals cannot carry prepayment penalties under RBI rules — prepaying early in the tenure is the single biggest interest saver." },
    ],
    related: ["emi-calculator", "car-loan-emi-calculator", "income-tax-calculator"],
  },
  {
    slug: "car-loan-emi-calculator",
    category: "finance",
    name: "Car Loan EMI Calculator",
    h1: "Car Loan EMI Calculator",
    tagline: "Work out your car loan EMI before you visit the showroom.",
    title: "Car Loan EMI Calculator — Auto Loan EMI (India)",
    description:
      "Free car loan EMI calculator. Find your monthly car loan EMI, total interest and total cost for any amount, rate and tenure — before the dealer does.",
    intro:
      "Know your EMI before the showroom does the math for you. Enter the loan amount, rate and tenure to see the monthly EMI and the true total cost of financing the car — preset with typical car-loan figures.",
    keywords: ["car loan emi calculator", "car loan calculator", "auto loan emi calculator", "vehicle loan emi"],
    component: "emi-calculator",
    params: { principal: 800000, rate: 9.5, years: 7 },
    volumeEstimate: 301000,
    howTo: [
      "Enter the amount you plan to finance (price minus down payment).",
      "Set the interest rate and tenure (3–7 years is typical).",
      "Read the monthly EMI and the total interest you'd pay.",
    ],
    faqs: [
      { q: "What tenure is best for a car loan?", a: "Shorter is cheaper: cars depreciate while interest accrues, so a 3–5 year loan keeps total interest down and avoids owing more than the car is worth." },
      { q: "Why is my dealer's 'flat rate' quote misleading?", a: "Dealers often quote flat rates, which charge interest on the full original amount throughout. A 6% flat rate costs about the same as an 11% reducing-balance rate — always compare EMIs, not quoted rates." },
      { q: "Should I make a bigger down payment?", a: "Usually yes: financing less of a depreciating asset saves interest outright and lowers the EMI. Keep an emergency buffer though — don't drain savings entirely for the down payment." },
    ],
    related: ["emi-calculator", "home-loan-emi-calculator", "discount-calculator"],
  },
  {
    slug: "tip-calculator",
    category: "finance",
    name: "Tip Calculator",
    h1: "Tip Calculator",
    tagline: "Work out the tip and split the bill between any number of people.",
    title: "Tip Calculator — Free Online Bill & Gratuity Splitter",
    description:
      "Free tip calculator. Enter the bill, choose a tip percentage, and split the total between any number of people. See tip, total and per-person amounts instantly.",
    intro:
      "Enter your bill amount, pick a tip percentage (or drag the slider), and choose how many people are splitting. You instantly get the tip, the grand total, and the amount each person owes — perfect for restaurants, cafes and group outings. Everything calculates live in your browser.",
    keywords: ["tip calculator", "gratuity calculator", "bill split calculator", "how much to tip"],
    component: "tip-calculator",
    volumeEstimate: 450000,
    howTo: [
      "Enter the bill amount.",
      "Choose a tip percentage with the buttons or slider.",
      "Set how many people are splitting the bill.",
      "Read the tip, total and per-person amounts.",
    ],
    faqs: [
      { q: "What is a standard tip percentage?", a: "In the US, 15–20% is typical for table service, with 18% a common default. Norms vary by country and service type, so adjust to your situation." },
      { q: "Is the tip calculated before or after tax?", a: "This calculator applies the tip percentage to the amount you enter. If you prefer to tip on the pre-tax subtotal, enter that figure as the bill." },
    ],
    related: ["discount-calculator", "percentage-calculator", "gst-calculator"],
  },
  {
    slug: "gpa-calculator",
    category: "finance",
    name: "GPA Calculator",
    h1: "GPA Calculator",
    tagline: "Calculate your grade point average on the 4.0 scale, weighted by credits.",
    title: "GPA Calculator — Free Online Grade Point Average Tool",
    description:
      "Free GPA calculator. Add your courses, letter grades and credit hours to get your weighted grade point average on the standard 4.0 scale. Instant, private.",
    intro:
      "Add each course with its letter grade and credit hours to compute your weighted GPA on the standard US 4.0 scale. Add or remove courses as needed; the average and total credits update instantly. Calculations run entirely in your browser — nothing is saved or uploaded.",
    keywords: ["gpa calculator", "grade point average calculator", "college gpa calculator", "weighted gpa calculator"],
    component: "gpa-calculator",
    volumeEstimate: 823000,
    howTo: [
      "Enter each course name, its letter grade and its credit hours.",
      "Add more courses with the Add course button.",
      "Read your weighted GPA on the 4.0 scale.",
    ],
    faqs: [
      { q: "How is GPA calculated?", a: "Each grade maps to grade points (A=4.0, B=3.0…). Multiply each course's points by its credits, sum them, and divide by total credits to get the credit-weighted average." },
      { q: "What grade scale does this use?", a: "The standard US 4.0 scale with +/− grades (A=4.0, A−=3.7, B+=3.3, and so on down to F=0.0)." },
    ],
    related: ["percentage-calculator", "tip-calculator"],
  },
  {
    slug: "step-up-sip-calculator",
    category: "finance",
    name: "Step Up SIP Calculator",
    h1: "Step Up SIP Calculator",
    tagline: "Project your SIP's maturity value when you increase it every year.",
    title: "Step Up SIP Calculator — Annual Top-Up SIP Returns",
    description:
      "Free step up SIP calculator. See how increasing your SIP by 5–15% every year grows your corpus, with a year-by-year table of invested amount and value.",
    intro:
      "A step-up (top-up) SIP increases your monthly investment by a fixed percentage every year, matching your salary increments. Enter your starting SIP, annual step-up, expected return and period to see the maturity value — and open the year-by-year table to watch the compounding accelerate. A 10% annual step-up typically grows the final corpus by 45–80% versus a flat SIP over 15+ years.",
    keywords: ["step up sip calculator", "top up sip calculator", "sip step up", "increasing sip calculator"],
    component: "step-up-sip-calculator",
    volumeEstimate: 135000,
    updated: "2026-06-13",
    howTo: [
      "Enter your starting monthly SIP amount.",
      "Set the annual step-up percentage (10% is a common default, matching salary growth).",
      "Enter the expected annual return and investment period.",
      "Read the maturity value, and open the year-by-year table to see the growth path.",
    ],
    faqs: [
      { q: "What is a step-up SIP?", a: "A SIP where the monthly contribution automatically increases by a fixed percentage every year — for example ₹10,000 growing 10% annually becomes ₹11,000 in year 2, ₹12,100 in year 3, and so on. Most fund platforms let you set this up once." },
      { q: "How much difference does a step-up make?", a: "A lot over long periods. Because the larger contributions also compound, a 10% annual step-up over 15–20 years typically produces 45–80% more corpus than keeping the SIP flat." },
      { q: "What step-up percentage should I choose?", a: "Match it to your realistic salary growth — 5–10% is common. The key is consistency: a modest step-up you sustain beats an aggressive one you cancel." },
    ],
    related: ["sip-calculator", "lumpsum-calculator", "swp-calculator"],
  },
  {
    slug: "ssy-calculator",
    category: "finance",
    name: "Sukanya Samriddhi Yojana Calculator",
    h1: "Sukanya Samriddhi Yojana (SSY) Calculator",
    tagline: "Calculate the maturity value of your daughter's SSY account.",
    title: "SSY Calculator — Sukanya Samriddhi Yojana Maturity Value",
    description:
      "Free Sukanya Samriddhi Yojana calculator. Enter your yearly deposit to see the maturity value at 21 years with the current 8.2% government rate. Updated quarterly.",
    intro:
      "Sukanya Samriddhi Yojana is a government-backed savings scheme for a girl child, offering one of the highest small-savings interest rates with full tax exemption (EEE). Deposits run for the first 15 years; the account matures 21 years after opening. Enter your planned yearly deposit (₹250 to ₹1.5 lakh) to project the maturity amount at the current rate.",
    keywords: ["sukanya samriddhi yojana calculator", "ssy calculator", "sukanya samriddhi calculator", "ssy maturity calculator"],
    component: "ssy-calculator",
    volumeEstimate: 110000,
    updated: "2026-06-13",
    updateNote: "8.2% rate (FY 2025-26)",
    howTo: [
      "Enter the amount you plan to deposit each year (₹250 – ₹1,50,000).",
      "Check the interest rate — we pre-fill the current government rate.",
      "Read the total deposited, interest earned and the maturity value at 21 years.",
    ],
    faqs: [
      { q: "How long do I deposit, and when does SSY mature?", a: "You deposit for the first 15 years from account opening; the account then keeps earning interest and matures 21 years after opening (or on the girl's marriage after she turns 18)." },
      { q: "Is SSY interest taxable?", a: "No. SSY has EEE status — the deposit qualifies under Section 80C, and both the interest and the maturity amount are fully tax-free." },
      { q: "Does the interest rate change?", a: "Yes. The government reviews small-savings rates every quarter. The rate is 8.2% as of FY 2025-26; your actual maturity value will reflect the rates declared over the years." },
    ],
    related: ["ppf-calculator", "fd-calculator", "rd-calculator"],
  },
  {
    slug: "epf-calculator",
    category: "finance",
    name: "EPF Calculator",
    h1: "EPF Calculator — Provident Fund Corpus at Retirement",
    tagline: "Project your Employees' Provident Fund balance at retirement.",
    title: "EPF Calculator — PF Corpus & Interest at Retirement",
    description:
      "Free EPF calculator. Project your provident fund corpus at retirement from your basic salary, with employee + employer contributions and 8.25% EPFO interest.",
    intro:
      "Estimate your EPF corpus at retirement from your monthly basic salary (plus DA). The calculator applies the statutory split — your 12%, plus the employer's 12% minus the 8.33% EPS diversion on wages up to ₹15,000 — and compounds the EPFO-declared interest monthly, with your salary growing annually. Open your payslip, copy the basic, and see where you'll land at 58.",
    keywords: ["epf calculator", "pf calculator", "provident fund calculator", "epf corpus calculator"],
    component: "epf-calculator",
    volumeEstimate: 27100,
    updated: "2026-06-13",
    updateNote: "8.25% EPFO rate (FY 2024-25)",
    howTo: [
      "Enter your current monthly basic salary + dearness allowance.",
      "Set your current age, retirement age and expected annual salary growth.",
      "Check the EPF interest rate (pre-filled with the latest EPFO declaration).",
      "Read your projected corpus, total contributions and interest earned.",
    ],
    faqs: [
      { q: "How much goes into EPF each month?", a: "You contribute 12% of basic+DA. Your employer also pays 12%, but 8.33% of wages (capped at a ₹15,000 wage base) is diverted to the pension scheme (EPS) — the rest joins your EPF balance." },
      { q: "What interest rate does EPF pay?", a: "EPFO declares the rate yearly — 8.25% for FY 2024-25. Interest is calculated on monthly running balances and credited annually, and it's tax-free within the contribution limits." },
      { q: "Can I withdraw EPF before retirement?", a: "Partial withdrawals are allowed for specific purposes (home purchase, medical, education) after minimum service periods, and the full balance after 2 months of unemployment — but early withdrawals sacrifice the most powerful compounding years." },
    ],
    related: ["nps-calculator", "ppf-calculator", "gratuity-calculator", "salary-calculator"],
  },
  {
    slug: "fire-calculator",
    category: "finance",
    name: "FIRE Calculator",
    h1: "FIRE Calculator — Financial Independence, Retire Early",
    tagline: "Find your FIRE number and how many years until you reach it.",
    title: "FIRE Calculator — Your Financial Independence Number",
    description:
      "Free FIRE calculator. Get your financial independence number from annual expenses and the 4% rule, and see how many years your savings rate needs to reach it.",
    intro:
      "FIRE (Financial Independence, Retire Early) reduces to one number: the portfolio that lets you withdraw your annual expenses indefinitely. With the classic 4% safe withdrawal rate, that's 25× your yearly spending. Enter your expenses, current savings, monthly investment and expected return to get your FIRE number and a realistic countdown to reaching it.",
    keywords: ["fire calculator", "financial independence calculator", "retire early calculator", "fire number"],
    component: "fire-calculator",
    volumeEstimate: 18100,
    updated: "2026-06-13",
    howTo: [
      "Enter your annual living expenses (what retirement actually costs you, not your income).",
      "Set a safe withdrawal rate — 4% is the classic baseline; 3–3.5% is more conservative.",
      "Enter current savings, your monthly investment and expected return.",
      "Read your FIRE number and the projected years to reach it.",
    ],
    faqs: [
      { q: "What is the 4% rule?", a: "A guideline from the Trinity study: withdrawing 4% of a diversified portfolio in year one (inflation-adjusted after) historically survived 30-year retirements. It implies needing 25× annual expenses; conservative planners use 3–3.5% (28–33×)." },
      { q: "Should I use pre-tax or post-tax expenses?", a: "Use your real annual spending including taxes you'll pay on withdrawals. Underestimating expenses is the most common FIRE planning error." },
      { q: "Does this account for inflation?", a: "Use a real (inflation-adjusted) return — e.g. 7% nominal minus 3% inflation ≈ 4% real — and the result reads in today's money, which is the honest way to plan." },
    ],
    related: ["net-worth-calculator", "swp-calculator", "sip-calculator", "compound-interest-calculator"],
  },
  {
    slug: "net-worth-calculator",
    category: "finance",
    name: "Net Worth Calculator",
    h1: "Net Worth Calculator",
    tagline: "Add what you own, subtract what you owe — your true financial position.",
    title: "Net Worth Calculator — Assets Minus Liabilities",
    description:
      "Free net worth calculator. Total your assets (cash, investments, property) and liabilities (loans, credit cards) to see your net worth instantly. Private, in-browser.",
    intro:
      "Net worth is the single clearest measure of financial health: everything you own minus everything you owe. Fill in your assets and liabilities — nothing you type leaves your browser — and track the number over time. Growing net worth (not income) is what financial progress actually looks like.",
    keywords: ["net worth calculator", "calculate net worth", "assets minus liabilities", "net worth tracker"],
    component: "net-worth-calculator",
    volumeEstimate: 27100,
    updated: "2026-06-13",
    howTo: [
      "Enter your assets: cash, investments, retirement accounts, property, vehicles.",
      "Enter your liabilities: loan balances, credit card debt, other debts.",
      "Read your net worth — and recheck it quarterly to track the trend.",
    ],
    faqs: [
      { q: "Should I include my home and car?", a: "Yes — at realistic resale value, with the loan balances under liabilities. Some people track a separate 'liquid net worth' that excludes the primary home, since you can't spend it without moving." },
      { q: "Is a negative net worth bad?", a: "It's common early on (student loans, new mortgage). What matters is the direction: paying down debt and investing both move the number up — track it quarterly rather than judging a single snapshot." },
      { q: "Is my financial data stored anywhere?", a: "No. Everything computes locally in your browser and disappears when you close the tab." },
    ],
    related: ["fire-calculator", "emergency-fund-calculator", "emi-calculator"],
  },
  {
    slug: "emergency-fund-calculator",
    category: "finance",
    name: "Emergency Fund Calculator",
    h1: "Emergency Fund Calculator",
    tagline: "How much you should keep aside, and how long until you're covered.",
    title: "Emergency Fund Calculator — How Much Should You Save?",
    description:
      "Free emergency fund calculator. Get your target fund from monthly expenses (3–12 months of cover), see how funded you are, and how fast you can close the gap.",
    intro:
      "An emergency fund is 3–12 months of essential expenses in instantly-accessible savings — the buffer that keeps a job loss or medical bill from becoming debt. Enter your essential monthly spending, pick a cover level, and see your target, how much of it you already have, and how many months of saving will close the gap.",
    keywords: ["emergency fund calculator", "emergency savings calculator", "how much emergency fund", "rainy day fund calculator"],
    component: "emergency-fund-calculator",
    volumeEstimate: 9900,
    updated: "2026-06-13",
    howTo: [
      "Enter your essential monthly expenses (rent, food, utilities, EMIs, insurance).",
      "Choose months of cover — 6 months is the standard recommendation.",
      "Enter your current emergency savings and monthly saving capacity.",
      "Read your target, your funded percentage and your time to goal.",
    ],
    faqs: [
      { q: "How many months should my emergency fund cover?", a: "6 months of essential expenses is the common target. Use 3 months if you have very stable income and low obligations; 9–12 if you're self-employed, single-income or in a volatile industry." },
      { q: "Where should I keep the emergency fund?", a: "Somewhere safe and instantly accessible — a high-yield savings account or sweep-in FD. Not equities: the fund's job is availability in a crisis, not returns." },
      { q: "Do I count only essential expenses?", a: "Yes — what you'd actually spend in a tight month (housing, food, utilities, insurance, loan payments), not your full lifestyle spending. That keeps the target honest and reachable." },
    ],
    related: ["net-worth-calculator", "fd-calculator", "rd-calculator"],
  },
  {
    slug: "percentage-increase-calculator",
    category: "finance",
    name: "Percentage Increase Calculator",
    h1: "Percentage Increase Calculator",
    tagline: "Find the percent change between two numbers — increase or decrease.",
    title: "Percentage Increase Calculator — Percent Change Between Two Numbers",
    description:
      "Free percentage increase calculator. Enter an initial and final value to get the percent increase or decrease and the absolute change, with the formula shown.",
    intro:
      "Enter where a number started and where it ended to get the percentage change — positive for an increase, negative for a decrease — along with the absolute difference and the exact formula used. Handy for price changes, salary hikes, traffic growth and test scores.",
    keywords: ["percentage increase calculator", "percent change calculator", "percentage difference", "percent increase formula"],
    component: "percentage-increase-calculator",
    volumeEstimate: 165000,
    updated: "2026-06-13",
    howTo: [
      "Enter the initial value.",
      "Enter the final value.",
      "Read the percentage change, the absolute change, and the worked formula.",
    ],
    faqs: [
      { q: "What is the percentage increase formula?", a: "(final − initial) ÷ |initial| × 100. For example, going from 80 to 100 is (100 − 80) ÷ 80 × 100 = +25%." },
      { q: "Why can't the initial value be zero?", a: "Percentage change measures growth relative to the starting point — with a starting point of zero, any change is infinite, so the result is mathematically undefined." },
      { q: "Is percentage increase the same as percentage difference?", a: "No. Percentage change is directional (from initial to final); percentage difference compares two values symmetrically against their average. This tool computes directional change, which is what most people mean." },
    ],
    related: ["percentage-calculator", "discount-calculator", "cagr-calculator"],
  },
  {
    slug: "zakat-calculator",
    category: "finance",
    name: "Zakat Calculator",
    h1: "Zakat Calculator",
    tagline: "Work out your zakatable wealth, the nisab, and the 2.5% due.",
    title: "Zakat Calculator — Calculate Zakat on Cash, Gold & Savings",
    description:
      "Free zakat calculator. Add cash, gold, silver, investments and business assets, subtract debts, check the nisab and get the 2.5% zakat due. Private, any currency.",
    intro:
      "Add up your zakatable wealth — cash, gold and silver, shares and funds, business inventory and money owed to you — subtract debts that are currently due, and compare the result against the nisab (87.48 g of gold or 612.36 g of silver at today's prices). If you're above the nisab and have held the wealth for a lunar year, zakat is 2.5%. Works in any currency, and nothing you enter leaves your browser.",
    keywords: ["zakat calculator", "calculate zakat", "zakat on savings", "nisab calculator", "zakat on gold"],
    component: "zakat-calculator",
    volumeEstimate: 22200,
    updated: "2026-06-13",
    howTo: [
      "Enter your cash, gold/silver value, investments, business assets and recoverable receivables.",
      "Subtract debts that are due now.",
      "Pick the nisab basis (silver is the safer, more charitable choice) and check the metal price per gram.",
      "If your net wealth is above the nisab, pay 2.5% as zakat.",
    ],
    faqs: [
      { q: "What is the nisab?", a: "The minimum wealth at which zakat becomes due: the value of 87.48 g of gold or 612.36 g of silver. Because silver gives a lower threshold, many scholars recommend it so more wealth qualifies for charity." },
      { q: "Which assets are zakatable?", a: "Cash and bank balances, gold and silver, trade/business inventory, shares and funds, crypto, and money reliably owed to you. Your home, car and personal household items are not zakatable." },
      { q: "Do I deduct my debts?", a: "Debts that are currently due (this month's bills, instalments payable now) are generally deducted. Long-term debt like a full mortgage balance is usually not deducted in full — ask a scholar for your situation." },
      { q: "When do I pay zakat?", a: "Once your wealth has stayed above the nisab for one full lunar (hijri) year. Many people fix their zakat date in Ramadan for the extra reward and to make it easy to remember." },
    ],
    related: ["net-worth-calculator", "percentage-calculator", "fd-calculator"],
  },
  {
    slug: "vat-calculator",
    category: "finance",
    name: "VAT Calculator",
    h1: "VAT Calculator — Add or Remove VAT",
    tagline: "Add VAT to a net price or back it out of a gross price, at any rate.",
    title: "VAT Calculator — Add or Remove VAT at 20%, 15%, 12.5%, 5%",
    description:
      "Free VAT calculator. Add VAT to a net amount or remove it from a gross amount at UK 20%, South Africa 15%, Philippines 12%, Nigeria 7.5% or any custom rate.",
    intro:
      "Enter an amount and a VAT rate to either add VAT (you have the net, ex-VAT price) or remove VAT (you have the gross, VAT-inclusive price). One-tap presets cover the UK's 20% standard and 5% reduced rates, South Africa's 15%, the Philippines' 12% and Nigeria's 7.5% — or type any rate. Handy for invoices, expenses and price checks.",
    keywords: ["vat calculator", "add vat", "remove vat", "vat calculator uk", "reverse vat calculator"],
    component: "vat-calculator",
    volumeEstimate: 201000,
    updated: "2026-06-13",
    updateNote: "UK 20% standard rate",
    howTo: [
      "Enter the amount.",
      "Pick a preset rate or type your country's VAT rate.",
      "Choose Add VAT if your amount is the net price, or Remove VAT if it already includes VAT.",
      "Read the net, VAT and gross amounts.",
    ],
    faqs: [
      { q: "How do I remove VAT from a price?", a: "Divide the gross price by (1 + rate). At the UK's 20%, a £120 gross price is £120 ÷ 1.2 = £100 net, so the VAT is £20 — note that it's not 20% of £120." },
      { q: "What are the common VAT rates?", a: "UK: 20% standard, 5% reduced, 0% zero-rated. South Africa: 15%. Philippines: 12%. Nigeria: 7.5%. Ireland: 23%. EU rates vary by country, typically 17–27%." },
      { q: "What's the difference between VAT and GST?", a: "They work the same way — a consumption tax added at each stage with credits for tax already paid. Different countries just use different names (VAT in the UK/EU/ZA, GST in India/Australia/Canada)." },
    ],
    related: ["gst-calculator", "discount-calculator", "percentage-calculator"],
  },
  {
    slug: "mortgage-calculator",
    category: "finance",
    name: "Mortgage Calculator",
    h1: "Mortgage Repayment Calculator",
    tagline: "Monthly repayments, total interest, LTV and a year-by-year schedule.",
    title: "Mortgage Calculator — Monthly Repayments & Amortization",
    description:
      "Free mortgage calculator. Get your monthly repayment from price, deposit, rate and term — plus total interest, loan-to-value and a year-by-year payoff schedule.",
    intro:
      "Enter the property price, your deposit, the interest rate and the term to see your monthly repayment on a standard capital-and-interest mortgage, along with the loan amount, loan-to-value (LTV) and total interest over the life of the loan. Open the year-by-year schedule to see how early payments are mostly interest — the key fact behind overpayment and remortgage decisions.",
    keywords: ["mortgage calculator", "mortgage repayment calculator", "home loan calculator", "mortgage interest calculator"],
    component: "mortgage-calculator",
    volumeEstimate: 450000,
    updated: "2026-06-13",
    howTo: [
      "Enter the property price and your deposit (down payment).",
      "Set the interest rate and the mortgage term in years.",
      "Read your monthly repayment, LTV and total interest.",
      "Open the year-by-year schedule to see principal vs interest over time.",
    ],
    faqs: [
      { q: "How is the monthly repayment calculated?", a: "With the standard amortization formula on a reducing balance: each payment covers that month's interest plus some principal, so the interest share shrinks every month while the principal share grows." },
      { q: "What is LTV and why does it matter?", a: "Loan-to-value is the loan as a percentage of the property price. Lower LTV bands (90%, 85%, 75%, 60%) unlock cheaper interest rates — a slightly bigger deposit can cut your rate meaningfully." },
      { q: "Do overpayments help?", a: "Yes — money paid early hits the balance when interest is at its highest, so even small regular overpayments cut years and a lot of interest. Check your deal's overpayment allowance (often 10% per year without penalty)." },
      { q: "Does this include taxes and insurance?", a: "No — it computes principal and interest only. Add buildings insurance, any property taxes and fees on top for a full cost picture." },
    ],
    related: ["emi-calculator", "home-loan-emi-calculator", "net-worth-calculator"],
  },
  {
    slug: "gst-calculator-australia",
    category: "finance",
    name: "GST Calculator (Australia)",
    h1: "Australian GST Calculator — Add or Remove 10% GST",
    tagline: "Add 10% GST to a price or back it out of a GST-inclusive total.",
    title: "GST Calculator Australia — Add or Remove 10% GST",
    description:
      "Free Australian GST calculator. Add 10% GST to an ex-GST price or work out the GST inside a total. Instant, accurate and free for invoices and BAS.",
    intro:
      "Australia charges a flat 10% GST on most goods and services. Enter an amount to add GST (you have the ex-GST price) or remove GST (you have the GST-inclusive total — the calculator divides by 11 to find the GST). Useful for invoices, quotes, expense claims and BAS preparation.",
    keywords: ["gst calculator australia", "australian gst calculator", "add gst", "gst exclusive calculator", "remove gst"],
    component: "gst-calculator",
    params: { rates: "10", defaultRate: 10, currency: "$", splitNote: false },
    volumeEstimate: 110000,
    updated: "2026-06-13",
    updateNote: "10% GST rate",
    howTo: [
      "Enter the amount in dollars.",
      "Choose Add GST if it's an ex-GST price, or Remove GST if it already includes GST.",
      "Read the base amount, the GST and the total.",
    ],
    faqs: [
      { q: "How do I work out the GST in a total?", a: "Divide the GST-inclusive total by 11. A $110 total contains $10 GST — because the total is 110% of the base, the GST is 10/110 = 1/11 of it." },
      { q: "What is exempt from GST in Australia?", a: "GST-free items include most basic food, many health and medical services, education courses and exports. Input-taxed items like residential rent and many financial services also carry no GST." },
      { q: "When must a business register for GST?", a: "Once GST turnover reaches $75,000 ($150,000 for non-profits), or immediately for taxi/ride-share drivers. Registered businesses charge 10% and claim credits for GST paid on inputs via their BAS." },
    ],
    related: ["gst-calculator", "vat-calculator", "discount-calculator"],
  },
  {
    slug: "superannuation-calculator",
    category: "finance",
    name: "Superannuation Calculator",
    h1: "Superannuation Calculator — Your Super at Retirement",
    tagline: "Project your Australian super balance from salary and employer contributions.",
    title: "Superannuation Calculator — Project Your Super Balance",
    description:
      "Free superannuation calculator. Project your super at retirement from salary, the 12% super guarantee, contributions tax and investment returns.",
    intro:
      "Estimate how your superannuation grows to retirement. The calculator applies the Super Guarantee (12% of salary since 1 July 2025), deducts the 15% contributions tax, grows your salary annually and compounds investment returns monthly on top of your current balance. Use a real (after-inflation) return to read the result in today's dollars.",
    keywords: ["superannuation calculator", "super calculator", "super balance calculator", "retirement calculator australia"],
    component: "superannuation-calculator",
    volumeEstimate: 40500,
    updated: "2026-06-13",
    updateNote: "12% SG rate (from Jul 2025)",
    howTo: [
      "Enter your annual salary and current super balance.",
      "Set your current age and planned retirement age.",
      "Check the Super Guarantee rate (12% since July 2025) and expected return.",
      "Read your projected balance, total contributions and investment growth.",
    ],
    faqs: [
      { q: "What is the Super Guarantee rate?", a: "The minimum your employer must contribute — 12% of ordinary time earnings since 1 July 2025, after rising in steps from 9.5%. It's paid on top of (or as part of) your package, into your super fund." },
      { q: "Why is 15% deducted from contributions?", a: "Employer and salary-sacrifice contributions are taxed at 15% on the way into the fund (less than most people's marginal rate, which is the incentive). This calculator deducts it before compounding." },
      { q: "Can I add extra to super?", a: "Yes — salary sacrifice or personal deductible contributions up to the concessional cap ($30,000 a year including employer contributions) get the same 15% tax treatment, and extra amounts can go in as non-concessional contributions." },
    ],
    related: ["retirement-calculator", "fire-calculator", "nps-calculator", "epf-calculator"],
  },
  {
    slug: "salary-to-hourly-calculator",
    category: "finance",
    name: "Salary to Hourly Calculator",
    h1: "Salary to Hourly Calculator",
    tagline: "Convert an annual salary to hourly, daily, weekly and monthly pay — or back.",
    title: "Salary to Hourly Calculator — Convert Annual Pay to Hourly Rate",
    description:
      "Free salary to hourly calculator. Convert annual salary to an hourly rate (and back) using your real hours per week and working weeks per year.",
    intro:
      "Convert between annual salary and hourly rate in either direction. Enter your hours per week and working weeks per year (use fewer than 52 to account for unpaid leave) and see your pay broken down as hourly, daily, weekly, monthly and annual — useful for comparing a salaried offer against contract or hourly work.",
    keywords: ["salary to hourly calculator", "salary to hourly", "annual salary to hourly rate", "hourly to salary calculator"],
    component: "salary-to-hourly-calculator",
    volumeEstimate: 49500,
    updated: "2026-06-13",
    howTo: [
      "Choose whether you know your annual salary or your hourly rate.",
      "Enter the amount, your hours per week, and working weeks per year.",
      "Read the equivalent hourly, daily, weekly, monthly and annual pay.",
    ],
    faqs: [
      { q: "How do I convert salary to an hourly rate?", a: "Divide the annual salary by your total working hours: hours per week × weeks per year. At 40 hours and 52 weeks, $50,000 ÷ 2,080 ≈ $24.04 per hour." },
      { q: "Why use fewer than 52 weeks?", a: "If your time off is unpaid (common for contractors), you only earn during working weeks — using 48 weeks instead of 52 shows the higher hourly rate you actually need to match a salary." },
      { q: "Are these figures before or after tax?", a: "Before tax (gross). Take-home pay depends on your country's income tax and social contributions." },
    ],
    related: ["salary-calculator", "overtime-pay-calculator", "percentage-calculator"],
  },
  {
    slug: "overtime-pay-calculator",
    category: "finance",
    name: "Overtime Pay Calculator",
    h1: "Overtime Pay Calculator",
    tagline: "Calculate time-and-a-half or double-time pay and your weekly total.",
    title: "Overtime Pay Calculator — Time and a Half & Double Time",
    description:
      "Free overtime pay calculator. Work out your overtime rate at 1.5× or 2×, the overtime pay for your extra hours, and your total weekly pay.",
    intro:
      "Enter your regular hourly rate, pick the overtime multiplier — time-and-a-half (1.5×) or double time (2×) — and add your regular and overtime hours to see your overtime rate, overtime pay and total weekly pay. In the US, the FLSA entitles most non-exempt employees to at least 1.5× for hours beyond 40 a week.",
    keywords: ["overtime pay calculator", "time and a half calculator", "overtime rate calculator", "double time calculator"],
    component: "overtime-pay-calculator",
    volumeEstimate: 3600,
    updated: "2026-06-13",
    howTo: [
      "Enter your regular hourly rate.",
      "Pick the multiplier: time-and-a-half (1.5×) or double time (2×).",
      "Enter your regular hours and overtime hours for the week.",
      "Read your overtime rate, overtime pay and weekly total.",
    ],
    faqs: [
      { q: "What is time and a half?", a: "1.5× your regular hourly rate. At $20/hour, overtime pays $30/hour — the FLSA minimum for non-exempt US employees working beyond 40 hours a week." },
      { q: "When does double time apply?", a: "US federal law doesn't require it, but some states (California beyond 12 hours/day), union agreements and contracts pay 2× for long days, Sundays or public holidays — check your own terms." },
      { q: "Who is exempt from overtime?", a: "In the US, salaried employees in executive, administrative or professional roles above a salary threshold are typically exempt. Most hourly workers are non-exempt and must receive overtime." },
    ],
    related: ["salary-to-hourly-calculator", "salary-calculator", "percentage-calculator"],
  },
  {
    slug: "salary-calculator-uk",
    category: "finance",
    name: "UK Salary Calculator",
    h1: "UK Salary Calculator — Take-Home Pay After Tax & NI",
    tagline: "Your monthly take-home from gross salary: income tax, NI, pension, student loan.",
    title: "UK Salary Calculator 2025/26 — Take-Home Pay After Tax & NI",
    description:
      "Free UK salary calculator for 2025/26. See your monthly take-home pay after income tax, National Insurance, pension and student loan, with a full breakdown.",
    intro:
      "Enter your gross annual salary to see your take-home pay for the 2025/26 tax year. The calculator applies the £12,570 personal allowance (with the £100k taper), the 20/40/45% income-tax bands, employee National Insurance at 8% and 2%, your pension contribution as salary sacrifice, and your student loan plan — with a line-by-line breakdown of where every pound goes.",
    keywords: ["salary calculator uk", "take home pay calculator", "uk tax calculator", "net salary calculator uk", "salary after tax uk"],
    component: "uk-salary-calculator",
    volumeEstimate: 368000,
    updated: "2026-06-13",
    updateNote: "2025/26 tax year",
    howTo: [
      "Enter your gross annual salary.",
      "Add your pension percentage (salary sacrifice) if you contribute.",
      "Pick your student loan plan, or leave as none.",
      "Read your monthly, annual and weekly take-home with the full deduction breakdown.",
    ],
    faqs: [
      { q: "What are the UK income tax bands for 2025/26?", a: "After the £12,570 personal allowance: 20% basic rate on the next £37,700 of taxable income, 40% higher rate up to £125,140, and 45% additional rate above. The allowance tapers away £1 per £2 of income over £100,000." },
      { q: "How much National Insurance do I pay?", a: "Employees pay 8% on earnings between £12,570 and £50,270 a year, and 2% above that — deducted through PAYE alongside income tax." },
      { q: "Why does salary sacrifice pension save money?", a: "Sacrificed salary never reaches you, so it escapes both income tax and NI — a 20% taxpayer effectively gets 28% relief. This calculator models pension that way; relief-at-source schemes differ slightly." },
      { q: "Does this work for Scotland?", a: "NI and student loans are UK-wide, but Scotland sets different income-tax bands (19%–48% across six bands), so Scottish take-home differs. This calculator uses England/Wales/NI bands." },
    ],
    related: ["national-insurance-calculator", "student-loan-repayment-calculator", "salary-to-hourly-calculator", "salary-calculator"],
  },
  {
    slug: "national-insurance-calculator",
    category: "finance",
    name: "National Insurance Calculator",
    h1: "National Insurance Calculator (UK)",
    tagline: "Your employee NI for 2025/26, with the band-by-band breakdown.",
    title: "National Insurance Calculator 2025/26 — Employee NI Contributions",
    description:
      "Free UK National Insurance calculator. See your Class 1 employee NI for 2025/26 — 8% and 2% bands — as monthly, annual and weekly amounts with a breakdown.",
    intro:
      "Enter your gross annual salary to see exactly how much employee National Insurance you pay in 2025/26: nothing below £12,570, 8% between £12,570 and £50,270, and 2% above that. The band table shows how much of your salary falls in each band and what it costs you.",
    keywords: ["national insurance calculator", "ni calculator", "class 1 national insurance", "how much national insurance do i pay"],
    component: "national-insurance-calculator",
    volumeEstimate: 6600,
    updated: "2026-06-13",
    updateNote: "2025/26 thresholds",
    howTo: [
      "Enter your gross annual salary.",
      "Read your monthly, annual and weekly NI.",
      "Check the band table to see how the total is built up.",
    ],
    faqs: [
      { q: "What are the NI rates for 2025/26?", a: "Employees pay 8% on earnings between the primary threshold (£12,570/year) and the upper earnings limit (£50,270/year), then 2% on everything above — cut from 12%/10% in 2024." },
      { q: "Does NI affect my State Pension?", a: "Yes. Years where you pay (or are credited with) NI count toward the 35 qualifying years needed for the full new State Pension — check your NI record on GOV.UK for gaps." },
      { q: "Do the self-employed pay the same?", a: "No — the self-employed pay Class 4 NI through Self Assessment (6% between £12,570 and £50,270, 2% above) and no longer pay Class 2." },
    ],
    related: ["salary-calculator-uk", "student-loan-repayment-calculator", "salary-to-hourly-calculator"],
  },
  {
    slug: "student-loan-repayment-calculator",
    category: "finance",
    name: "Student Loan Repayment Calculator",
    h1: "Student Loan Repayment Calculator (UK)",
    tagline: "What you'll repay monthly on Plan 1, 2, 4, 5 or postgraduate loans.",
    title: "Student Loan Repayment Calculator UK — Plan 1, 2, 4, 5 & Postgrad",
    description:
      "Free UK student loan repayment calculator. See your monthly and annual repayments for Plan 1, 2, 4, 5 and postgraduate loans at 2025/26 thresholds.",
    intro:
      "Pick your loan plan and enter your salary to see what you actually repay: 9% of income above your plan's threshold (6% for postgraduate loans), taken automatically through PAYE. The 2025/26 thresholds are built in — Plan 1 £26,065, Plan 2 £28,470, Plan 4 £32,745, Plan 5 £25,000, postgraduate £21,000.",
    keywords: ["student loan repayment calculator", "student loan calculator uk", "plan 2 student loan", "how much student loan do i repay"],
    component: "student-loan-repayment-calculator",
    volumeEstimate: 12100,
    updated: "2026-06-13",
    updateNote: "2025/26 thresholds",
    howTo: [
      "Enter your gross annual salary.",
      "Choose your plan (your loan paperwork or the SLC portal confirms which).",
      "Read your monthly and annual repayment and the threshold that applies.",
    ],
    faqs: [
      { q: "Which student loan plan am I on?", a: "England/Wales before 2012: Plan 1. England/Wales 2012–2023: Plan 2. Scotland: Plan 4. England from August 2023: Plan 5. Master's/doctoral loans: postgraduate plan. Check your online SLC account if unsure." },
      { q: "Do I repay anything below the threshold?", a: "No. Repayments are only taken on the part of your income above your plan's threshold — earn below it and you pay nothing, and repayments pause automatically if your income drops." },
      { q: "Can I repay more than one loan at once?", a: "Yes — an undergraduate plan and a postgraduate loan repay simultaneously (9% + 6% on income above each threshold), which this calculator shows one plan at a time." },
    ],
    related: ["salary-calculator-uk", "national-insurance-calculator", "loan-prepayment-calculator"],
  },
  {
    slug: "capital-gains-tax-calculator",
    category: "finance",
    name: "Capital Gains Tax Calculator",
    h1: "Capital Gains Tax Calculator (UK 2025/26)",
    tagline: "CGT on shares, crypto and property at the 18% and 24% rates.",
    title: "Capital Gains Tax Calculator UK — 2025/26 CGT on Shares & Property",
    description:
      "Free UK capital gains tax calculator for 2025/26. Applies the £3,000 allowance and 18%/24% rates based on your income band — see your CGT and after-tax gain.",
    intro:
      "Enter your total gain and your taxable income to work out UK capital gains tax for 2025/26. The calculator deducts the £3,000 annual exempt amount, fills your unused basic-rate band at 18%, and taxes the rest at 24% — the rates that have applied to all assets (shares, funds, crypto and property alike) since 30 October 2024.",
    keywords: ["capital gains tax calculator", "cgt calculator", "capital gains tax uk", "cgt on shares", "capital gains tax on property"],
    component: "capital-gains-tax-calculator",
    volumeEstimate: 18100,
    updated: "2026-06-13",
    updateNote: "2025/26 rates & £3,000 allowance",
    howTo: [
      "Enter your total capital gain for the year (sale proceeds minus costs).",
      "Enter your taxable income (salary etc.) — it determines how much gain is taxed at 18% vs 24%.",
      "Read your CGT bill and after-tax gain.",
    ],
    faqs: [
      { q: "What is the CGT allowance for 2025/26?", a: "£3,000 per person per year (the annual exempt amount). Gains within it are tax-free; couples can use both allowances by holding assets jointly." },
      { q: "What are the CGT rates now?", a: "18% for gains within your unused basic-rate band and 24% above it — the same rates for all asset types since 30 October 2024, including residential property." },
      { q: "What's exempt from CGT?", a: "Your main home (private residence relief), ISAs and pensions, gifts to a spouse, personal possessions sold under £6,000, and your car. Crypto is NOT exempt — disposals are taxable like shares." },
    ],
    related: ["salary-calculator-uk", "cagr-calculator", "net-worth-calculator"],
  },
  {
    slug: "retirement-calculator",
    category: "finance",
    name: "Retirement Calculator",
    h1: "Retirement Calculator — Corpus & Sustainable Income",
    tagline: "Project your retirement savings and the monthly income they can support.",
    title: "Retirement Calculator — How Much Will You Have at Retirement?",
    description:
      "Free retirement calculator. Project your savings to retirement age from monthly contributions and returns, and see the sustainable monthly income they support.",
    intro:
      "Enter your age, retirement age, current savings and monthly contribution to project your retirement corpus with monthly compounding — then see the income it can sustainably pay using your chosen withdrawal rate (4% is the classic baseline). Currency-agnostic: use a real (after-inflation) return and everything reads in today's money.",
    keywords: ["retirement calculator", "retirement savings calculator", "retirement corpus calculator", "how much do i need to retire"],
    component: "retirement-calculator",
    volumeEstimate: 368000,
    updated: "2026-06-13",
    howTo: [
      "Enter your current age and planned retirement age.",
      "Add your current savings and monthly contribution.",
      "Set the expected return and a withdrawal rate for retirement.",
      "Read your projected corpus and the monthly income it supports.",
    ],
    faqs: [
      { q: "How much do I need to retire?", a: "A common rule: 25× your annual expenses (the 4% rule). If you spend 40,000 a year, aim for about 1,000,000 — adjust with a more conservative 3–3.5% withdrawal rate for longer retirements." },
      { q: "Should I use nominal or real returns?", a: "Real (after-inflation) returns — e.g. 7% nominal minus 3% inflation ≈ 4% real. Then the projected corpus and income are in today's purchasing power, which is far easier to sanity-check." },
      { q: "Does this include pensions like 401(k), EPF or super?", a: "Treat those balances as part of current savings and their inflows as part of the monthly contribution. For scheme-specific rules, see our EPF, NPS and superannuation calculators." },
    ],
    related: ["fire-calculator", "superannuation-calculator", "nps-calculator", "epf-calculator"],
  },
  {
    slug: "loan-prepayment-calculator",
    category: "finance",
    name: "Loan Prepayment Calculator",
    h1: "Loan Prepayment Calculator — Interest Saved & Tenure Cut",
    tagline: "See what a lump-sum prepayment saves: shorter tenure vs lower EMI, compared.",
    title: "Loan Prepayment Calculator — Interest Saved by Part Payment",
    description:
      "Free loan prepayment calculator. See how a lump-sum part payment cuts your tenure or EMI, and exactly how much interest each option saves on your loan.",
    intro:
      "Enter your outstanding balance, rate, remaining tenure and the lump sum you want to prepay. The calculator compares both options banks offer: keep the same EMI and finish months early, or keep the tenure and lower the EMI — showing the interest saved by each, side by side. Keeping the EMI almost always saves far more, because prepaid money hits the balance while interest is front-loaded.",
    keywords: ["loan prepayment calculator", "part payment calculator", "home loan prepayment", "prepayment interest savings"],
    component: "loan-prepayment-calculator",
    volumeEstimate: 5400,
    updated: "2026-06-13",
    howTo: [
      "Enter your outstanding balance, interest rate and remaining months.",
      "Enter the one-time prepayment amount.",
      "Compare Option A (same EMI, shorter tenure) with Option B (same tenure, lower EMI).",
    ],
    faqs: [
      { q: "Should I reduce the EMI or the tenure?", a: "Reduce the tenure (keep the EMI) if you can afford to — the balance falls faster while interest is at its highest, so total interest saved is usually several times larger than the same-tenure option." },
      { q: "Are there prepayment penalties?", a: "Floating-rate home loans to individuals in India carry no prepayment penalty by RBI rules. Fixed-rate and personal loans may charge 2–5% — check your agreement and net it against the savings." },
      { q: "When does prepaying make the most difference?", a: "Early in the loan, when most of each EMI is interest. The same lump sum prepaid in year 2 saves far more than in year 12." },
    ],
    related: ["emi-calculator", "home-loan-emi-calculator", "mortgage-calculator"],
  },
  {
    slug: "tds-calculator",
    category: "finance",
    name: "TDS Calculator",
    h1: "TDS Calculator — Tax Deducted at Source (FY 2025-26)",
    tagline: "TDS on interest, rent, contractor, commission and professional fees.",
    title: "TDS Calculator — Section-wise TDS Rates FY 2025-26",
    description:
      "Free TDS calculator for FY 2025-26. Pick the section — 194A interest, 194C contractor, 194H commission, 194I rent, 194J professional fees — and get the TDS and net payable.",
    intro:
      "Select the nature of payment and the amount to compute TDS at the correct section rate for FY 2025-26 — 10% on bank interest (194A), 1–2% on contractor payments (194C), 2% on commission (194H), 2%/10% on rent (194I) and 10%/2% on professional or technical fees (194J). Toggle PAN off to see the 20% rate under section 206AA. Salary TDS follows your slab instead — use the income tax calculator for that.",
    keywords: ["tds calculator", "tds rate chart", "tds on rent", "tds on professional fees", "194j tds rate"],
    component: "tds-calculator",
    volumeEstimate: 8100,
    updated: "2026-06-13",
    updateNote: "FY 2025-26 rates",
    howTo: [
      "Pick the section that matches the payment (interest, rent, contractor, commission, professional fees).",
      "Enter the payment amount.",
      "Set whether the payee has furnished PAN.",
      "Read the TDS to deduct and the net amount payable.",
    ],
    faqs: [
      { q: "What happens without PAN?", a: "Section 206AA applies: TDS at the higher of the section rate or 20%. Furnishing PAN (or linking it with Aadhaar — unlinked PAN counts as inoperative) avoids the punitive rate." },
      { q: "Are there thresholds below which no TDS applies?", a: "Yes, per section — e.g. ₹50,000/year for bank interest under 194A, ₹30,000 per contract under 194C, ₹50,000/month rent for individuals under 194-IB. Below the threshold, deduct nothing." },
      { q: "Is TDS my final tax?", a: "No — it's an advance collection. Your actual liability is computed at return filing; excess TDS comes back as a refund, shortfall is paid as self-assessment tax. Track credits in Form 26AS/AIS." },
    ],
    related: ["income-tax-calculator", "salary-calculator", "hra-calculator"],
  },
  {
    slug: "youtube-earnings-calculator",
    category: "finance",
    name: "YouTube Earnings Calculator",
    h1: "YouTube Earnings Calculator — Estimate Your Ad Revenue",
    tagline: "Estimate monthly and yearly YouTube income from views and your niche's RPM.",
    title: "YouTube Earnings Calculator — How Much Do YouTubers Make?",
    description:
      "Free YouTube earnings calculator. Estimate monthly and yearly ad revenue from your views and RPM, with realistic per-niche presets from finance to gaming.",
    intro:
      "Enter your monthly views and an RPM — your revenue per 1,000 views after YouTube's share — to estimate ad earnings. Niche presets give realistic starting points: finance and business channels often earn $6–12 RPM while entertainment and gaming sit nearer $1–2, which is why two channels with identical views can earn 10× apart.",
    keywords: ["youtube earnings calculator", "youtube money calculator", "how much do youtubers make", "youtube rpm calculator"],
    component: "youtube-earnings-calculator",
    volumeEstimate: 6600,
    updated: "2026-06-13",
    howTo: [
      "Enter your average monthly views.",
      "Pick your niche preset or type your actual RPM from YouTube Analytics.",
      "Read the estimated monthly and yearly ad revenue.",
    ],
    faqs: [
      { q: "What is RPM vs CPM?", a: "CPM is what advertisers pay per 1,000 ad impressions; RPM is what YOU receive per 1,000 video views after YouTube's ~45% share and non-monetized views. RPM is the number that predicts your payout — find yours in YouTube Analytics." },
      { q: "Why do niches earn such different amounts?", a: "Advertisers bid more to reach high-intent audiences: finance, B2B software and insurance viewers are worth more per click than entertainment viewers, pushing RPM up 5–10×." },
      { q: "What are the monetization requirements?", a: "The YouTube Partner Program needs 1,000 subscribers plus either 4,000 public watch hours in 12 months or 10M Shorts views in 90 days, then ad revenue, memberships and Super Thanks unlock." },
    ],
    related: ["percentage-calculator", "salary-to-hourly-calculator", "cagr-calculator"],
  },
];
